### ISSUE TITLE
BAG Identifier velden als strings in DB opnemen

### ISSUE THREAD

**Issue by justb4** [nlextract/NLExtract#108]
Alle identificatie velden van BAG Objecten zijn Strings. XML definitie:

```
<xs:simpleType name="Objectnummer">
    <xs:annotation>
        <xs:documentation>Uniek objectaanduiding binnen een gemeente, bestaande uit 16 cijfers.</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
        <xs:maxLength value="16"/>
    </xs:restriction>
</xs:simpleType>
```

Heel vaak hebben die idenitifiers "voorloopnullen". In NLextract-BAG worden deze velden geconverteerd en in Database ingelezen als Integers (`identificatie NUMERIC(16)`) . Daarmee gaan de voorloopnullen verloren. Intern allemaal niet zo'n probleem. Echter veel software gaat uit van Strings (met voorloopnullen) als BAG identificatie-velden en halen daar mogelijk ook types uit. Hoewel het wat achaïsch aandoet en voorloopnullen erg "ponskaartachtig" klinkt ;-)  lijkt het toch beter om Strings aan te houden.

**Comment by justb4** [comment]
Uitstellen: voor nu te ingrijpend.

**Comment by justb4** [comment]
Hmm, er ligt juist ander voorstel voor BigInt identifiers: #200

**Comment by jwva** [comment]
De voorloopnullen hebben betekenis. Het zijn i.h.a. de nullen die je ook in de CBS gemeentecodes ziet. De eerste vier karakters van een BAG sleutel duiden dus een gemeente aan. Bij het Instituut Fysieke Veiligheid gebruiken we de BAG sleutels om te matchen met andere databases (o.a. WOZ, Handelsregister, LRKP). Met de huidige numerieke BAG sleutels in NLExtract gaat dat mis; we moeten er nu zelf scriptmatig voorloopnullen links aan plakken. Het zou mooi zijn als NLExtract de BAG sleutels gewoon conform de definitie als string kan leveren.

**Comment by fsteggink** [comment]
Voor PDOK Locatieserver laten we ook de voorloopnullen intact van de BAG.

**Comment by justb4** [comment]
Ik dacht nog aan een "post-processing" SQL script met `ALTER TABLE` en `lpad` etc om optioneel kolom conversie te doen, maar wordt voor gebruikers ondoorzichtig. Laten we gewoon maar de schema/code wijzigen, moet kijken naar impact en tijd, tijd.

**Comment by jwva** [comment]
Is er al iets te zeggen over wanneer @Just of misschien iemand anders hier wat tijd voor kan vrijmaken? 
Alvast bedankt.

**Comment by tino** [comment]
Ja, of je laat de legacy achter, en matched met een gecaste big int ipv voorloopnullen scripten. Het zijn tenslotte cijfers in de definitie 🤗

**Comment by XtheOne** [comment]
Ik had ook gekeken naar bigint, maar dan is het nog niet zomaar duidelijk hoeveel voorloopnullen er voor moeten. ook een bigint is een getal welke je moet omzetten in een string met voorloopnullen.

**Comment by tino** [comment]
Oh, oke. Ik was ga er dan wel een beetje van uit gegaan dat dat aangevuld moet to 16, gezien de definitie.

**Comment by jwva** [comment]
Hoi,

 

Volgens mij klopt dat. Het zijn altijd 16 karakters (altijd cijfers), die met een nul kunnen beginnen, afhankelijk van de gemeentecode. Om met andere bronbestanden te matchen op deze sleutel, zijn die voorloopnullen wel van belang. Ook in het gemeentebestand van CBS zijn die voorloopnullen van belang. 

 

Met hartelijke groet,

 

Jan-Willem van Aalst

 <mailto:jw@imergis.nl> jw@imergis.nl

06-42746848

 

 

 

Van: Tino de Bruijn [mailto:notifications@github.com] 
Verzonden: maandag 30 oktober 2017 14:53
Aan: nlextract/NLExtract <NLExtract@noreply.github.com>
CC: jwva <geo@imergis.nl>; Comment <comment@noreply.github.com>
Onderwerp: Re: [nlextract/NLExtract] BAG Identifier velden als strings in DB opnemen (#108)

 

Oh, oke. Ik was ga er dan wel een beetje van uit gegaan dat dat aangevuld moet to 16, gezien de definitie.

**Comment by XtheOne** [comment]
maxLength = 16 zegt mij dat het niet per definitie aangevuld moet worden met voorloopnullen tot lengte 16. Wie weet hoe het zit mag het zeggen, ik weet het niet 100% zeker.
Een idee is om optioneel nieuwe recordnamen welke numeric (16) zijn en via een script te vullen vanuit de nieuwe string velden zodat met minimale aanpassingen bestaande koppelingen (tijdelijk) bruikbaar zijn.
Beste is natuurlijk om een bestaande koppeling aan te passen naar strings, maar zo maak je de overgang makkelijker.

**Comment by jwva** [comment]
Hoi,

 

In de BAG definitie heeft een sleutelveld altijd eenzelfde aantal karakters. Een BAG sleutel is *geen* numeriek getal. Dit komt door de CBS-definitie van de gemeentecodes. In Groningen bijv. kan een gemeente als code “0006” hebben. Dit zijn de eerste vier karakters van de BAG sleutel. Die voorloopnullen doen er dus toe. Zelf kan ik nu de BAG niet koppelen met bijv. WOZ-gegevens, Handelsregister gegevens, Risicokaart en LRKP (kinderopvang) gegevens, omdat die wel voorloopnullen registeren en ik dus probeer een string met een getal te matchen. Ik pleit er dan ook voor om het NLExtract van de BAG te gaan publiceren met datatype string(16) voor de sleutelvelden.

 

Met hartelijke groet,

 

Jan-Willem van Aalst

 <mailto:jw@imergis.nl> jw@imergis.nl

06-42746848

 

 

 

Van: Michel [mailto:notifications@github.com] 
Verzonden: maandag 30 oktober 2017 21:34
Aan: nlextract/NLExtract <NLExtract@noreply.github.com>
CC: jwva <geo@imergis.nl>; Comment <comment@noreply.github.com>
Onderwerp: Re: [nlextract/NLExtract] BAG Identifier velden als strings in DB opnemen (#108)

 

maxLength = 16 zegt mij dat het niet per definitie aangevuld moet worden met voorloopnullen tot lengte 16. Wie weet hoe het zit mag het zeggen, ik weet het niet 100% zeker.
Een idee is om optioneel nieuwe recordnamen welke numeric (16) zijn en via een script te vullen vanuit de nieuwe string velden zodat met minimale aanpassingen bestaande koppelingen (tijdelijk) bruikbaar zijn.
Beste is natuurlijk om een bestaande koppeling aan te passen naar strings, maar zo maak je de overgang makkelijker.

**Comment by justb4** [comment]
Code en schema is gewijzigd, met dank aan @borrob, om 16 char identifiers (4 chars voor woonplaats id) te gebruiken. Test bezig op http://data.nlextract.nl/bag

- "oude" BAG januari 2018 (met int identifiers): DB tabellen en dumps is bewaard
- BAG januari 2018 (met char(16) identifiers): opnieuw in DB lezen en dumps aanmaken
- verschillen vergelijken: bijv zijn er precies evenveel adressen, hoe verhoudt zich de grootte van de dumps, ter latere analyse eventuele issues

Als alles in orde ook dit issue sluiten.

**Comment by justb4** [comment]
Onder https://data.nlextract.nl/bag staan de PG en adres CSV dumps van januari 2018 die voorloopnullen bevatten. Bij eerste inspectie alles ok. Ter vergelijking zijn de dumps van jan 2018 met integer id's bewaard onder resp:

https://data.nlextract.nl/bag/postgis/jan18-intids/ en
https://data.nlextract.nl/bag/csv/jan18-intids/

Ik sluit dit issue nu. Mocht er toch iets zijn, heropenen.
