### ISSUE TITLE
geo_postcode4.geopunt en geo_postcode6.geopunt staan niet in het midden

### ISSUE THREAD

**Issue by tompesman** [nlextract/NLExtract#115]
Bij het gebruik van de `geo_postcode4.geopunt` en `geo_postcode6.geopunt` kwam ik erachter dat deze worden gevuld door een enkel coördinaat. Dus bijvoorbeeld de pc4 postcode van '2613' wordt gevuld door het eerste adres in de postcode 2613 range. Hetzelfde geldt voor de pc6, daarbij wordt het eerste huis in een straat gepakt. Is hier een reden voor, of zal ik een PR maken waarbij het midden gebruikt wordt van een hele straat voor de pc6 en een heel postcodegebied bij pc4?

voorbeeld voor pc6:

``` sql
SELECT ST_Centroid(ST_Extent(geopunt)) FROM bag.geo_adres WHERE postcode = '1234AB';
```

voorbeeld voor pc4:

``` sql
SELECT ST_Centroid(ST_Extent(geopunt)) FROM bag.geo_adres WHERE postcode LIKE '1234%';
```

**Comment by milovanderlinden** [comment]
Dit klinkt in mijn ogen als een klassieke voronoi. Naast de centroides van de postcodegebieden wil je ook een landsdekkend postcodebestand zonder gaten. Het lijkt mij een goed idee om als deze functie is geimplementeerd eens te testen of voronoi nauwkeurig genoeg blijkt en dan eventueel de functie vervangen.

https://smathermather.wordpress.com/2013/12/21/voronoi-in-postgis/

**Comment by justb4** [comment]
Voronoi:  dacht ik ook aan..

**Comment by tompesman** [comment]
En dan van het vlak de centroid pakken?

**Comment by borrob** [comment]
Misschien is het sneller om `ST_PointOnSurface` te gebruiken? Dat zou gegarandeerd een punt op de geometrie moeten geven (werkt met punt, lijn en vlak). Let wel: niet per se een punt in het midden of op het zwaartepunt, maar wel binnen de geometrie.

Zie: [http://postgis.refractions.net/docs/ST_PointOnSurface.html](ST_PointOnSurface).

**Comment by justb4** [comment]
Ik sluit deze: al 8 jaar geen activiteit, en is bovendien BAG v1 code.
