### ISSUE TITLE
Nummeraanduidingen zonder postcode

### ISSUE THREAD

**Issue by fsteggink** [nlextract/NLExtract#137]
In de views nummeraanduidingactueel en nummeraanduidingactueelbestaand worden nummeraanduidingen zonder postcode (where postcode is null) niet meegenomen. Volgens mij is dit niet per se fout. Op deze site van het Kadaster staat ook niet dat het niet geldig is: http://www.kadaster.nl/web/Themas/Registraties/BAG/BAGartikelen/Basisregistratie-Adressen.htm

Deze views wordt aangemaakt in het bestand /bag/db/script/bag-view-actueel-bestaand.sql
De wijziging waarbij er wordt gecheckt op postcode is null is in de volgende commit doorgevoerd: https://github.com/opengeogroep/NLExtract/commit/26f0678e4e9d06b9a194d19e6bdd79532c40f191#diff-67c38a0cfcff32a7de3d053a1f60d920

Een voorbeeld van een nummeraanduiding zonder postcode is 826200000024660 (Vondelinghof 11-G01 in Oosterhout). Aan de toevoeging te zien gaat het om een garagebox. In de tabel nummeraanduiding is te zien dat er twee voorkomens zijn. De eerste (niet meer geldig) bevat wel een postcode, maar de tweede (de huidige) niet. Het verblijfsobject dat hier naar verwijst (via hoofdadres) bestaat wel in verblijfsobjectactueelbestaand.

**Comment by gidema** [comment]
Ik ben het er mee eens dat nummeraanduidingen met postcode IS NULL niet uitgefilterd zouden moeten worden in de views nummeraanduidingactueel en nummeraanduidingactueelbestaand.
Postcodes zijn alleen toegewezen aan panden waar daadwerkelijk post bezorgd kan worden. Naast garages zijn bijvoorbeeld tranformatorhuisjes panden met een huisnummer, maar zonder postcode.
Weet iemand nog waarom de check op postcode is null destijds is toegevoegd?

**Comment by justb4** [comment]
On 07-09-15 22:09, Gertjan Idema wrote:
> Ik ben het er mee eens dat nummeraanduidingen met postcode IS NULL niet
> uitgefilterd zouden moeten worden in de views nummeraanduidingactueel en
> nummeraanduidingactueelbestaand.
> Postcodes zijn alleen toegewezen aan panden waar daadwerkelijk post
> bezorgd kan worden. Naast garages zijn bijvoorbeeld tranformatorhuisjes
> panden met een huisnummer, maar zonder postcode.
> Weet iemand nog waarom de check op postcode is null destijds is toegevoegd?
Weet niet meer precies, maar had dacht ik met geldige adressen te maken. 
Andere reden, meen ik, dat in de BAG bronbestanden soms ongeldige 
postcodes voorkomen, die worden op NULL gezet tijdens inlezen.

Ik sta open om de restrictie weg te halen, maar de impact, bijv op de 
adres CSV, moet goed bekeken worden.

**Comment by Quiet-Wildcard** [comment]
Beste Justin,

Enkele jaren heb ik dankbaar gebruik gemaakt van CSV exports op https://nlextract.nl/

Sinds het niet meer gratis is ben ik genoodzaakt zelf de data met jullie geweldige tool te bouwen.
Ik gebruik de tool voornamelijk om te kijken waar nieuwbouw wordt aangekondigd. (bouwvergunning verleend sloop etc) en om de nieuwe adressen te filteren met de huidige lijst.
Wellicht doe ik dat geheel omslachtig, maar voor mij werkt het.

Bovenstaand issue is mij ook opgevallen.

Er zijn adressen welke wel een nummeraanduidingen hebben, maar geen postcode... wel een huisnummer en straatnaam toekenning.

Zelf draai ik nu de inspireadressen om naar bruikbare csv. in 
PostgreSQL 12
pgadmin4-4.23
QGis Desktop 3.14

Allemaal in Windows 7 :)

Het zou mooi zijn als ook de panden worden meegenomen zonder postcode.

Is dat dan zo simpel als de nummeraanduiding.postcode is NOT NULL aanpassen naar NULL?
Afijn, ik ga het gewoon is proberen en testen.... wordt vervolgd.... Gisteren om 22 inmiddels weer de nieuwe inspireadressen online :)

Wat bedoelt u anders met " Ik sta open om de restrictie weg te halen, maar de impact, bijv op de
adres CSV, moet goed bekeken worden"

Met dank ook aan @geertdoornbos  welke mij vorige maand heeft geholpen. En het beschikbaar stellen van de documentatie

Nog een vraagje,
Staat er nog dit jaar een update op de planning op NLextract v1.4.3 en deze met Python 3.8.4 en hoger te laten werken?

**Comment by SanderH** [comment]
> Ik sta open om de restrictie weg te halen, maar de impact, bijv op de
> adres CSV, moet goed bekeken worden.

Volgens mij is de impact vooral dat je dan compleet bent met je adressen ipv incompleet. Er zullen vast toepassingen zijn waar het niet hebben van een postcode 'vervelend' is, maar dat is dan eenvoudig te ondervangen door op de adrestabel een filter toe te passen en eventueel op de CSV's een variant met en zonder postcodes te leveren?

In ieder geval mogen van mij de postcodes erbij. Had een hele zoektocht om te achterhalen waarom ik bepaalde adressen mistte en bleek uiteindelijk hierin verstopt te zitten...

**Comment by justb4** [comment]
M.i.v. NLExtract 1.5.2 voor BAG 2.0 worden alle adressen-tabellen direct van "adres-plus" afgeleid. Dit script van PeeWee neemt zoveel mogelijk adressen mee, ondanks fouten in de BAG en missende postcodes. Zie laatste versie:
https://github.com/nlextract/NLExtract/blob/master/bagv2/etl/sql/adres/adres-tabel-plus.sql

De oude BAG (1.0) gaan we niet meer onderhouden want is m.i.v. mei 2021 in gecontroleerde versie uitgefaseerd door Kadaster. Wees blij dat we in NLExtract nu al een BAG 2.0 versie hebben!

Er zijn gewoon adressen zonder postcodes, trafo-huisjes bijv. Denk niet alleen aan je eigen use-case.
We willen in eerste plaats zoveel mogelijk adressen "vangen". Je kunt altijd (bijv geen postcode) uitfilteren.

Ik zou zeggen review bovenstaand script, we moeten samen alles op alles zetten om met BAG 2.0 om te gaan.

**Comment by justb4** [comment]
In BAGv2 worden ook adressen zonder postcode meegenomen, dit zijn geldige, vaak triviale (brughuisjes, "PEN"-huisjes) gebouwen, of nog niet toegekend. Over en sluiten.
