### ISSUE TITLE
Onderscheid geometrietypen?

### ISSUE THREAD

**Issue by fsteggink** [nlextract/NLExtract#163]
Uit een mail die ik aan Just heb gestuurd:

Een aantal featureklassen in de BGT / IMGeo kunnen verschillende soorten geometrieën hebben. Bijv. een "scheiding" kan een lijn of een vlak zijn, dus heb ik dit vertaald naar geometrietype 0 in de GFS, dus alles toegestaan. Zal ik de geometrietypen nog verder uitsplitsen, dus onderscheid maken in Xxx_2D_punt, _lijn, _vlak en _multivlak?

**Comment by jwva** [comment]
Met de BGT PostGIS dump van 28 december jl. ervaar ik geen problemen in QGIS. "Scheiding" is daar in de praktijk altijd een lijn (voor zover ik heb gemerkt). Uitsplitsen per geometrietype is op zich zuiverder, maar dan moet daar ook wel aanleiding voor zijn in de data... en dat ben ik nog niet tegengekomen.

**Comment by fsteggink** [comment]
In QGIS begint het openen van de BGT-database aardig lang te duren. Hij blijft hangen op de tabellen met meerdere geometrietypen, om te bepalen welk type wordt gebruikt. Dit gaat om de tabellen Kunstwerkdeel, Overigescheiding, Scheiding, Sensor, Vegetatieobject, Waterinrichtingselement en Weginrichtingselement.

**Comment by fsteggink** [comment]
Afgelopen week ben ik bezig geweest met BGT-extract. Bij PostGIS 2.2 en hoger wordt dit onderscheid gemaakt. Bij PostGIS 2.1 is dit wenselijk, maar omdat ST_ForceCurve hierbij niet werkt (wat nodig is ivm andere aanpassingen), werkt het nog niet. Work in progress.

**Comment by fsteggink** [comment]
Issue is opgelost in commit 7909d50 en anderen. :tada:
Het probleem was dat oude Postgresql versies (9.0 en 9.1) geen variabelenamen lijken te ondersteunen in functies. Deze heb ik dus vervangen door $1.

**Comment by fsteggink** [comment]
Op onze server kan ik het nog niet testen. Dit ligt aan de oude GDAL-versie (2.1) die nog wat problemen ("hacks" letterlijk) heeft met CityGML, wat in 2.2 gefixt is.
Ik sluit dit issue nu af, want ik ben tevreden.

**Comment by justb4** [comment]
Ja we moeten GDAL naar 2.2 upgraden op NLExtract server. Ik weet niet meer precies de status (of was dat PostGIS?) maar leek veel werk m.n. Python-GDAL koppeling. Je mag het van mij doen, je hebt toch toegang?
