### ISSUE TITLE
BAG inlezen met bounding box

### ISSUE THREAD

**Issue by fsteggink** [nlextract/NLExtract#174]
Er is behoefte om de BAG in te lezen met behulp van een bounding box. Hierdoor wordt het aantal records dat wordt ingelezen beperkt, alhoewel natuurlijk wel alle GML-bestanden doorgespit moeten worden. Het voordeel is dat de database minder groot wordt. Het is ook mogelijk dat het inlezen met een bounding box sneller gaat dan het inlezen van een volledige dump in combinatie met het uitvoeren van ruimtelijke queries met filtering op bounding box voor een export.

Een nadeel is dat niet alle BAG-objecten een geometrie hebben, dus ook geen bounding box. Een mogelijke optie is het achteraf uitfilteren van dergelijke objecten. Voorbeelden hiervan zijn nummeraanduidingen en openbare ruimtes.

**Comment by fsteggink** [comment]
Wellicht dit oppakken wanneer BAG naar Stetl wordt geport. Dan zou dit d.m.v. een spatial extent bij ogr2ogr geïmplementeerd kunnen worden.
Ik weet trouwens niet meer waar deze behoefte oorspronkelijk geuit is.

**Comment by justb4** [comment]
Ik sluit deze dan, na 8 jaar! Wat wel evt nuttig kan zijn is filteren op Gemeente. De gemeentecode zit in de BAG identifiers (behalve Woonplaats). .
