### ISSUE TITLE
Docker package NLExtract

### ISSUE THREAD

**Issue by fsteggink** [nlextract/NLExtract#192]
Voor Stetl heeft Just al een package gemaakt: https://github.com/justb4/stetl/issues/36
Het ligt voor de hand dit ook voor NLExtract te maken. Dit vergemakkelijkt de deployment in een OTAP-straat, maar het kan ook gebruikt worden voor unit testing.

**Comment by petericebear** [comment]
Dit of een Vagrant image file om een virtuele machine te starten die de conversie kan doen zou echt tof zijn.

**Comment by holtkamp** [comment]
Sinds februari 2020 zijn de NLExtract Downloads betaald aangeboden via www.geotoko.nl

Dit maakt het gebruik van een Docker image om de extract "zelf" te kunnen extra interessant. 

Alleen kan ik het resultaat van https://github.com/nlextract/NLExtract/commit/5a214fa23c3edd7bdbc7be3aa63407c19860c6dd niet meer in de huidige master branch vinden, klopt dat?

Wat verder zoeken geeft:
https://github.com/nlextract/docker => dd 18-02-2020, maar vrij leeg
https://hub.docker.com/u/nlextract/ => dd 01-07-2016, maar geen repositories

Samenvattend, wat is de status van Docker ondersteuning? @justb4, is het plan om dit werk in https://github.com/nlextract/docker te bundelen?

Mogelijk kan ik bijdragen 👍

**Comment by justb4** [comment]
Ja https://github.com/nlextract/docker  en Docker Hub is daarvoor bedoeld. @stvno had daarbij de lead. Ik weet dat er veel "zelf geklust" is met NLExtract Docker images (gek genoeg ikzelf nog niet, tijdgebrek), maar totnutoe is er niets in GitHub gedeeld.

**Comment by holtkamp** [comment]
bedankt voor de snelle reactie @justb4, @stvno is er een branch waar ik eens naar kan kijken en pogen het zelf ook aan de praat te krijgen en de bevindingen delen?

**Comment by sandervanhooft** [comment]
Een hoop bekende gezichten hier :).

Is er nieuws wat betreft Docker support?

**Comment by justb4** [comment]
Ja [Dockerfile](https://github.com/nlextract/NLExtract/blob/master/Dockerfile) is er al een tijdje, ook op [DockerHub](https://hub.docker.com/repository/docker/nlextract/nlextract/tags?page=1&ordering=last_updated), dus sluit deze.
