### ISSUE TITLE
Maak BAG-extract multithreaded

### ISSUE THREAD

**Issue by fsteggink** [nlextract/NLExtract#194]
BAG-extract is een ideale applicatie om multithreaded te maken, aangezien een BAG-extract uit meerdere GML-bestanden bestaat en op een (server of desktop) omgeving wordt uitgevoerd waar meerdere processoren of cores beschikbaar zijn.

Zie ook https://github.com/justb4/stetl/issues/41

**Comment by justb4** [comment]
Sluiten: dit is een duplicate van #126.
