### ISSUE TITLE
NLExtract GitHub repo verhuizen naar NLExtract GH organization

### ISSUE THREAD

**Issue by justb4** [nlextract/NLExtract#195]
On July 27, 2016 the GH repo https://github.com/opengeogroep/NLExtract/ will be moved to https://github.com/nlextract the NLExtract organization on GH. This issue is a checklist of TODOs for this transfer. Items in Italic are done.

- _execute transfer to https://github.com/nlextract_
- _exec `git remote set-url origin https://github.com/nlextract/nlextract` in local project_
- _all refs in GH repo in particular Sphinx documentation to new repo_
- _website: http://nlextract.nl updates_
- _notify contributors and other interested parties (NLExtract mailing list, Dutch OSGeo)_
- _update NLExtract Gitter naar https://gitter.im/nlextract/NLExtract_
- _newsitem verhuizing op website: http://nlextract.nl_ : https://sites.google.com/site/nlextractnl/project-updates/nlextractgithubrepoisverhuisd

**Comment by fsteggink** [comment]
Ik kan in Gitter geen optie vinden om de chat room te verhuizen van opengeogroep/NLExtract naar nlextract/NLExtract. Heb in de Gitter chat (https://gitter.im/gitterHQ/gitter) een vraag hierover gesteld.

**Comment by justb4** [comment]
Idd kon dit ook nergens vinden, hopelijk helpen ze je. Anders maar een nieuwe Gitter room onder NLExtract, mogelijk kunnen we een screenshot oid van de chats totnutoe invoegen

**Comment by fsteggink** [comment]
Ik heb een nieuwe room aangemaakt en een mail verstuurd met een verzoek om de berichten te verhuizen.

**Comment by justb4** [comment]
Ok, gezien!

**Comment by fsteggink** [comment]
De verhuizing is gelukt, maar dat heb je al gezien.

**Comment by justb4** [comment]
All done!
