### ISSUE TITLE
Derde dimensie BAG-extract wordt niet gebruikt

### ISSUE THREAD

**Issue by fsteggink** [nlextract/NLExtract#198]
Op 22-08 jl. gemeld op de mailinglijst n.a.v. de fix voor PR #197 door Matthijs Laan:

> Wat ik mij nog wel afvraag is waarom het een 3D geometrie is. De Z coordinaat is altijd 0. Als ik bijvoorbeeld een 2D versie van de pand tabel maak is deze maar liefst 1,6 GB kleiner volgens pg_total_relation_size!

In een BAG-extract wordt voor alle geometrieën de 3e dimensie opgegeven, m.u.v. woonplaats. Hetzij d.m.v. srsDimension (vlakken) of 3 waarden (punten).

Een mogelijke oplossing is een configuratievariabele waarmee kan worden opgegeven of de geometrieën 2D of 3D moeten zijn. Het betekent wel mogelijke gevolgen voor de  uitwisseling / vervanging van BAG-extracten, omdat de geometriedefinitie verschilt.

Misschien hier naar kijken nadat BAG is geport naar Stetl? Ondanks het extra ruimtegebruik is er verder niks stuk, dus zie ik dit als een wens.

**Comment by justb4** [comment]
Kunnen we m.i. sluiten. In BAG v2 zijn alle geometrieën 2D.
