### ISSUE TITLE
BAG voor identifiers bigint gebruiken ipv numeric

### ISSUE THREAD

**Issue by tino** [nlextract/NLExtract#200]
`numeric` is voor getallen met een decimaal, en dat zijn de identifiers niet. Het type `bigint` (gaat t/m `+9223372036854775807`) lijkt mij beter geschikt.

Dit voorkomt ook dat je in applicatie code (bv. Python) een `decimal.Decimal` terug krijgt.

**Comment by justb4** [comment]
ja! vreemd dat niemand dat ooit eerder heeft opgemerkt. Er was wel ooit 'kritiek' dat de 'voorloopnullen' verdwijnen met een numeriek type, zodat string-type zoals in bron-BAG voor de hand zou liggen: zie #108. Maar van ``numeric`` naar ``bigint`` zou mogelijk wat opleveren in performance/storage en lijky me aller eerst gewenst. Heb je een mogelijkheid om een PR te leveren?

**Comment by justb4** [comment]
Helaas we gaan dit niet doen: er zijn veel verzoeken om de BAG identificatie velden "as-is" dus als strings met voorloopnullen, op te nemen, zie m.n. #108.
