### ISSUE TITLE
BRK extract: veldlengte voor kadastrale sectie moet 2 zijn ipv 1

### ISSUE THREAD

**Issue by justb4** [nlextract/NLExtract#201]
Het bestand [brk.gfs](https://github.com/nlextract/NLExtract/blob/master/brk/etl/gfs/brk.gfs) bepaalt hoe/welke velden OGR uit de bron GML worden geextraheerd en hun mapping naar kolommen (namen, types) in de (PostGIS) database. Als een veld een string is kan daarvoor een lengte gezet. Maar OGR bezit soms ook intelligentie dat hij lengte bepaalt op "wat ie het eerst tegenkomt". 

Het veld ``sectie`` (kadastrale sectie) in BRK ``Perceel.gml`` is meestal 1 letter bijv ``A``, ``B`` etc maar kan soms 2 letters zijn ``AA``, ``AG`` etc. In [brk.gfs](https://github.com/nlextract/NLExtract/blob/master/brk/etl/gfs/brk.gfs) staat nu echter een veldlengte van 1. Daardoor wordt bij inlezen de 2e letter "afgekapt". Door op 2 te zetten wordt dit hersteld. Zie bijv plaatje aangehecht voor perceel met kad_key: ``EMN00 AG 01884 G0000``. Boven is met veldlengte 1, onder met lengte 2 in [brk.gfs](https://github.com/nlextract/NLExtract/blob/master/brk/etl/gfs/brk.gfs).

![nlx-brk-sectionnr-cutoff](https://cloud.githubusercontent.com/assets/582630/19393722/49cc445e-9236-11e6-9830-4335b9eaa85b.jpg)

**Comment by justb4** [comment]
Gefixed!

**Comment by fsteggink** [comment]
Top!
