### ISSUE TITLE
BRK-DKK download script moet ook met expliciete mapnaam werken

### ISSUE THREAD

**Issue by justb4** [nlextract/NLExtract#202]
Het  script [download-brk.sh](https://github.com/nlextract/NLExtract/tree/master/brk/etl) om BRK van PDOK te downloaden, werkte voorheen met een argument waarin doel-directory gezet moest worden. Ergens is dit veranderd en staat de directory nu vast op ``leveringen/latest``. Dit maakt dit script beperkt toepasbaar in andere omgevingen. 

Door nu een optioneel "doel-map" argument toe te voegen met een default van ``leveringen/latest`` kunnen toch beide mogelijkheden bestaan. Ook een check of de directory wel bestaat wordt geintroduceerd.

**Comment by justb4** [comment]
getest en kan in 1.2.1

**Comment by fsteggink** [comment]
Dit was gesneuveld in de refactoring in 31aad07 :(
