### ISSUE TITLE
BGT rotatie openbareruimtelabel foutief

### ISSUE THREAD

**Issue by danielrobins** [nlextract/NLExtract#203]
De rotatie van de openbare ruimte labels staat soms verkeerd. Het lijkt erop dat bij een langere straat met 2 of meer labels, de verkeerde rotatie meegegeven wordt. 

Voorbeeld: Groenedijk in Mill. Hier staat echter geen pand dus kan je geen adres geven. Coordinaten die erbij horen: 182730,411175
Adres vlakbij: Kasteelsestraat 6 in Mill. Gaat om de straat daar vlak boven.

De straat maakt vanaf de Beerseweg een bocht naar het noorden toe. In de bron van de gemeente staat de straatnaam 2x. De meest linkse heeft een hoek van 0,9 graden en de ander een hoek van 39,5. In de dump staan de meest linkse met de hoek horende bij de ander.
Op de PDOK viewer staat dit wel goed en staan ze er beide op.
In de BGT dump komt deze slechts 1 maal voor

PDOK zie ik Slagwerkpad in Almere 3x staan. Op de BGT dump zie ik er maar 1 terug. (Overigens klopt in dit geval de rotatie op PDOK ook niet)

**Comment by fsteggink** [comment]
Zojuist geantwoord via de mailinglijst:
> Bedankt voor het aanmaken van het issue. Ik heb er naar gekeken, maar het blijkt dat de fout al in de brondata zit. Ik heb een 2x2 km bestand van zowel Almere als Mill gedownload, met daarin de genoemde straten. In beide bestanden komt het openbareruimtelabel met de naam 'Slagwerkpad' resp. 'Groenedijk' slechts één keer voor (bgt_openbareruimtelabel.gml).
> 
> Blijkbaar gaat er e.e.a. mis bij het verwerken door PDOK. Klaarblijkelijk beschikken zij wel over de juiste data, want anders kunnen zij niet meerdere labels tonen in de viewer. Ik vond het al vreemd dat de rotatie wordt overgenomen. In eerste instantie verdacht ik ons ontdubbelscript (bgt\etl\sql\delete-duplicates-v2.1.1.sql), maar hier worden geen gegevens van verschillende records gecombineerd.
> 
> Ik zal het bij PDOK melden en je naam hierbij vermelden.

**Comment by fsteggink** [comment]
Een OpenbareRuimteLabel-feature kan _meerdere_ posities hebben. De GML moet hier opgesplitst worden. Ook moet erop worden gelet dat het ID uniek blijft (i.v.m. de deduplicatie).

**Comment by danielrobins** [comment]
Hallo Frank,

tevens op de NLExtract lijst gezet:

als ik dezelfde GML van Mill open zie ik toch echt 2 
plaatsbepalingspunten. Zit het daar niet in, dat slechts 1 van deze 2 
punten meegenomen wordt?
Hier het stukje code uit de gml:

<cityObjectMember>
<imgeo:OpenbareRuimteLabelgml:id="b18404013-524a-11e6-968e-abf0ea1ae068">
<creationDatexmlns="http://www.opengis.net/citygml/2.0 
<http://www.opengis.net/citygml/2.0>">2016-01-25</creationDate>
<imgeo:LV-publicatiedatum>2016-07-22T11:04:12.000</imgeo:LV-publicatiedatum>
<imgeo:relatieveHoogteligging>0</imgeo:relatieveHoogteligging>
<imgeo:inOnderzoek>false</imgeo:inOnderzoek>
<imgeo:tijdstipRegistratie>2016-05-09T09:09:39.000</imgeo:tijdstipRegistratie>
<imgeo:identificatie>
<imgeo:NEN3610ID>
<imgeo:namespace>NL.IMGeo</imgeo:namespace>
<imgeo:lokaalID>G0815.7df1b8ceea7a459984930e1926f05f65</imgeo:lokaalID>
</imgeo:NEN3610ID>
</imgeo:identificatie>
<imgeo:bronhouder>G0815</imgeo:bronhouder>
<imgeo:bgt-statuscodeSpace="http://www.geostandaarden.nl/imgeo/def/2.1#Status 
<http://www.geostandaarden.nl/imgeo/def/2.1#Status>">bestaand</imgeo:bgt-status>
<imgeo:plus-statuscodeSpace="http://www.geostandaarden.nl/imgeo/def/2.1#VoidReasonValue 
<http://www.geostandaarden.nl/imgeo/def/2.1#VoidReasonValue>">geenWaarde</imgeo:plus-status>
<imgeo:identificatieBAGOPR>0815300000000081</imgeo:identificatieBAGOPR>
<imgeo:openbareRuimteNaam>
<imgeo:Label>
<imgeo:tekst>Groenedijk</imgeo:tekst>
<imgeo:positie>
<imgeo:Labelpositie>
<imgeo:plaatsingspunt>
<gml:Pointxmlns:gml="http://www.opengis.net/gml 
<http://www.opengis.net/gml>">
<gml:pos>182943.866 411246.234</gml:pos>
</gml:Point>
</imgeo:plaatsingspunt>
<imgeo:hoek>-35.9</imgeo:hoek>
</imgeo:Labelpositie>
</imgeo:positie>
<imgeo:positie>
<imgeo:Labelpositie>
<imgeo:plaatsingspunt>
<gml:Pointxmlns:gml="http://www.opengis.net/gml 
<http://www.opengis.net/gml>">
<gml:pos>182719.869 411174.140</gml:pos>
</gml:Point>
</imgeo:plaatsingspunt>
<imgeo:hoek>-0.9</imgeo:hoek>
</imgeo:Labelpositie>
</imgeo:positie>
</imgeo:Label>
</imgeo:openbareRuimteNaam>
<imgeo:openbareRuimteTypecodeSpace="http://www.geostandaarden.nl/imgeo/def/2.1#TypeOpenbareRuimte 
<http://www.geostandaarden.nl/imgeo/def/2.1#TypeOpenbareRuimte>">Weg</imgeo:openbareRuimteType>
</imgeo:OpenbareRuimteLabel>
</cityObjectMember>

Met vriendelijke groet,

Daniël Robins
GISArts
www.gisarts.nl
06 13526214

Op 22-10-2016 12:01, Frank Steggink schreef:

**Comment by fsteggink** [comment]
Hoi Daniël, het issue is gefixed. Ik hoefde alleen de XSLT aan te passen, maar het was wel een vervelende aanpassing vanwege de structuur van de openbareruimtelabels. Ook moest ik ervoor zorgen dat de lokaal ID's uniek bleven, i.v.m. de deduplication.

**Comment by fsteggink** [comment]
Ik zal ook op de server de BGT-extract bijwerken, zodat overmorgen (2 nov.) de BGT-dump alle labels bevat.
Het is me wel opgevallen dat in Almere labels met dezelfde tekst op dezelfde plek staan, maar met een andre rotatie. Waarschijnlijk een poging van de gemeente om de foute rotatie te corrigeren. Alleen zijn ze vergeten om de oude labels vervallen te verklaren. Ook hebben ze dit niet consistent doorgevoerd. Bijv. er zijn maar 3 labels Slagwerkpad. Fagotstraat heeft 6 labels, 3 met de goede en 3 met de verkeerde rotatie.
