### ISSUE TITLE
Gewijzigde download BRK

### ISSUE THREAD

**Issue by fsteggink** [nlextract/NLExtract#204]
Vandaag is er via de PDOK attenderingsservice en bericht gekomen dat de BRK download gaat veranderen. Zie https://www.pdok.nl/nl/actueel/nieuws/artikel/31okt16-downloaden-digitale-kadastrale-kaart. Ze gaan hetzelfde concept als voor de BGT gebruiken. Op dit moment is er nog geen volledige (landelijke) download beschikbaar.
Tegen de tijd dat de data op de nieuwe downloadlocatie actueel is (medio november), moet onze BRK-download hierop worden aangepast.

**Comment by fsteggink** [comment]
Opgelost in commit e2dd7ebb739c4dd883c351100fb3300cef850442 en anderen.

**Comment by justb4** [comment]
Lastig te vinden wat nu de officiele download is, en hoe je die "blokken" weet? Bijv op https://www.pdok.nl/nl/producten/pdok-downloads/basisregistratie-kadaster/digitale-kadastrale-kaart kun je toch heel NL downloaden? Geen Atomfeeds meer?

**Comment by justb4** [comment]
In nieuwe download in blokken https://github.com/nlextract/NLExtract/blob/master/brk/etl/download-brk.sh ontbreken percelen in ieder geval in de Noordzee. Bijvoorbeeld gemeente NZE03 sectie A perceelnummer 95. Omliggende percelen zitten wel in download. Het lijkt steeds te gaan om buitenste percelen. Het kan zijn dat het betreffende blok niet wordt meegenomen. NZE03 A 95 ligt bijv ver in Noordzee (plaatje):
![noordzee-percelen-kadviewer](https://cloud.githubusercontent.com/assets/582630/23620177/4eedb60e-0296-11e7-9c67-41d4f0a8a276.jpg)

 en in blok als op kaart.
![noordzee-percelen](https://cloud.githubusercontent.com/assets/582630/23619875/62944c8c-0295-11e7-9dfd-e3ac7ff50cf0.jpg) 

Omliggende percelen zoals nummer 94 en 96, 97, 98 worden wel meegenomen. Of kan toch iets misgaan in extractie proces? Maar het zijn vooral percelen in periferie in Noordzee, dus vermoed dat er blokken ontbreken, maar ken de nummer-conventie daarvan niet.

Hier nog een paar shots huidig en voorheen:

![image](https://cloud.githubusercontent.com/assets/582630/23620210/5bcadb40-0296-11e7-877b-7e5a06c5fe87.png)

Voorheen:
![image](https://cloud.githubusercontent.com/assets/582630/23620225/6884e812-0296-11e7-88aa-682e29236724.png)

**Comment by fsteggink** [comment]
Bedankt voor het melden, Just.

De volgende blokken blijken nog te ontbreken: 44, 47, 144, 147, 153, 155, 183, 226 en 227.
Getest door alleen de blokken met gemeente like 'NZE%' te laden, hierover in QGIS een grid te tekenen met extent (-4000,296000,284000,648000) en spacing 32 km, en vervolgens deze blokken aan te klikken op de BRK-download pagina van PDOK.

Was jij nog bezig met het aanpassen van het laadscript, of laat je het zo? Ik zal zometeen een commit doen met de nieuwe blokken erbij.

Op termijn moeten we weer over naar volledige bestanden. Eerst tijd vinden om in #211 te duiken en dit op te lossen. Ik durf nu nog niet voor de BRK het volledige bestand te gebruiken.

**Comment by justb4** [comment]
Bedankt voor snelle actie! Nee, ik ben nergens mee bezig, dus ga je gang. Daarna wil ik evt aanpassing doen, bijv `kadastrale-aanduiding` key aanmaken. Maar we moeten wel een melding maken bij Kadaster/PDOK dat dit de drempel wel heel hoog maakt mbt Open Data. Ook de PDOK `kadastralekaartv3` heeft kuren: metadata is generiek (geen datum), WMS alleen zeer diep ingezoomd zichtbaar, WFS heeft geen `kadastrale-aanduiding` veld meer, TMS lijkt niet te werken,  etc.  Maar is ander issue...of een leuke niche voor NLExtract/map5.nl ;-).

**Comment by justb4** [comment]
Ik ga nu elders uitproberen en heb ook de NLExtract versie op kademo:/opt/nlextract/git  geupdate. Ligt dat aan ons dat die download zo traag is?

**Comment by fsteggink** [comment]
Just, is het issue opgelost en kan het gesloten worden?

Voor de zekerheid is het beter om heel NL te gaan gebruiken. Zie de link op https://www.pdok.nl/nl/producten/pdok-downloads/basisregistratie-kadaster/digitale-kadastrale-kaart. De HTTP range header zou moeten werken. Dit geldt ook voor de BGT. Het lijkt er naar op dat #211 opgelost is. Ik ga hiervoor een issue opvoeren.

**Comment by justb4** [comment]
Ok, wist niet van de heel NL download. Lijkt mij idd beter om te gebruiken, met `robust-download.sh`.

**Comment by fsteggink** [comment]
Geen reactie en wat mij betreft opgelost, dus ik sluit het issue.
