### ISSUE TITLE
Verwijderen bestaande input bij BGT import

### ISSUE THREAD

**Issue by skinkie** [nlextract/NLExtract#205]
Ik krijg het idee dat de bestaande tabel vulling wordt verwijderd wanneer etl-imgeo.sh opnieuw wordt gedraaid. Is er een manier om dit te voorkomen?

**Comment by fsteggink** [comment]
Dat klopt. Dit gebeurt in het script drop-tables-v2.1.1.sql.
Waarom zou je dat willen voorkomen? De BGT wordt alleen als volledige levering beschikbaar gesteld. Heb jij mutatiebestanden die je zou willen werken? Ik weet niet of en, zo ja, waar die worden aangeboden.

**Comment by skinkie** [comment]
Wat denk je van iets stoms als een volle schijf door een gml bestand van 151GB? Dan wil ik niet al het werk wat in de afgelopen uren gedaan is eerst in rook zien opgaan omdat iemand zo nodig een drop-tables scripts moet uitvoeren. Het zou mij logisch lijken dat een tabel pas wordt verwijderd als de inhoud van de tabel wordt vervangen. Hoe dan ook: ik wil sowieso nog wat pull requests gaan doen, ik ben op zich nu wel een tevreden gebruiker, maar er zitten nog te veel rariteiten in de code.

**Comment by justb4** [comment]
@skinkie don't beat the coders :-), we kunnen niet alle use-cases voorzien: de eerste/huidige implementatie doet "alles ineens" in 3 stappen: tabellen aan/leegmaken, inlezen, post-processing (duplicates, indexes/views).  Doordat dit proces gedreven wordt door een [Stetl configuratie](../blob/master/bgt/etl/conf/etl-imgeo-v2.1.1.cfg) via (bash/cmd) [scripts](../blob/master/bgt/etl/etl-imgeo.sh),  is er veel meer mogelijk (i.t.t. hardcoded implementatie). 

Bijv de ``[etl]`` sectie in [Stetl configuratie](../blob/master/bgt/etl/conf/etl-imgeo-v2.1.1.cfg) wordt bij default geheel uitgevoerd. Echter het ``stetl`` commando kent ook de ``-s --section`` optie waarmee een specifieke ``[sectie]`` uitgevoerd kan worden. Zodoende kunnen de 3 stappen in de huidige ``[etl]`` sectie (default) uitgesplitst worden in meerdere ``[secties]`` en via command line args in de [scripts](../blob/master/bgt/etl/etl-imgeo.sh) expliciet uitgevoerd worden, net als bij NLExtract BAG. Default kan zijn "alles ineens" maar met bijv ``-c --create``, ``-e --extract`` (of ``--append``) etc opties uitgesplitst. Een andere mogelijkheid is de [Stetl configuratie](../blob/master/bgt/etl/conf/etl-imgeo-v2.1.1.cfg) uitsplitsen tot 3 configs voor de 3 stappen. Er is dus op simpele wijze veel mogelijk. We willen dit wel uniform over alle datasets (BGT, BRK, Top10) houden, ook met oog op toekomstige gui.

**Comment by skinkie** [comment]
Ik zie het echter niet als drie stappen. Immers je laadt een bestand met specifieke kenmerken, dat bestand zou volgens jullie filosofie iets vervangen. Waarom zou de create stap geen onderdeel van het extract proces kunnen zijn? Op dat moment gaat het nooit automatisch mis.

**Comment by fsteggink** [comment]
Ideeën hoe dit beter op te lossen zijn van harte welkom. Zelf maak ik meestal een 2e database of schema aan voordat ik data ga laden. Natuurlijk is dat een teken dat het beter zou moeten, maar ik vind deze workaround goed genoeg, dus ik besteed mijn tijd liever aan andere zaken.

Deze discussie geldt ook voor de andere Stetl-gebaseerde ETL's.

**Comment by fsteggink** [comment]
Bij het laden van de BGT wordt de data eerst in een tijdelijke tabel (bijv. bak_2d_tmp) geladen en vervolgens in de definitieve (bijv. bak_2d). Een van de dingen die bij het maken van de definitieve tabel gebeurt, is het casten van bepaalde velden naar date/timestamp, zie #206.

Een eenvoudige oplossing is dat in het begin alleen de tijdelijke tabellen worden verwijderd en de definitieve tabellen pas worden verwijderd nadat de tijdelijke tabellen volledig zijn geladen en gededupliceerd.

Bij nadere inspectie heb ik het vermoeden dat de deduplicatie niet goed gaat. Deze wordt op de definitieve tabellen uitgevoerd en niet op de tijdelijke tabellen. Het is ook beter om de ongebruikte tabellen (bijv. bak en bak_lod0) uit alle scripts weg te halen, omdat die alleen voor verwarring zorgen. Lod0 zou alleen gebruikt hoeven worden wanneer deze data gevuld is.

**Comment by fsteggink** [comment]
Ik zit eraan te denken de oplossing die ik in mijn laatste post beschrijf te implementeren, namelijk in  begin alleen de tijdelijke tabellen weggooien en pas na de ogr2ogr stap de definitieve tabellen.

Een nadeel is wel het ruimtebeslag. Je hebt dan 2x zoveel ruimte nodig om de data in te laden. Die ruimte heb je trouwens ook nodig als je eerst een backup maakt van het oude schema.

We moeten er ook voor zorgen dat NLExtract stopt wanneer er fouten worden geconstateerd. Ik vraag me af of hier al voldoende checks op zijn, maar dat staat los van dit issue. Bij het recent laden van de BGT op de NLExtract server heb ik gemerkt dat NLExtract gewoon doorgaat wanneer er door OGR2OGR fouten worden gerapporteerd en niet alle data wordt geladen.

**Comment by fsteggink** [comment]
Ik heb de oplossing zoals beschreven op 31 januari geïmplementeerd. Wel heb ik een apart script toegevoegd waarmee de definitieve tabellen vooraf verwijderd kunnen worden, aangezien ik dat zelf prettiger vind werken, i.v.m. het ruimtebeslag.
