### ISSUE TITLE
BGT/stetl datum tijd als String

### ISSUE THREAD

**Issue by skinkie** [nlextract/NLExtract#206]
Waarom is er gekozen voor String om datum/tijd objecten uit de BGT GML te verwerken als String?

https://github.com/nlextract/NLExtract/blob/master/bgt/etl/meta/imgeo-v2.1.1-gfs-template.xml#L38

**Comment by fsteggink** [comment]
Volgens mij had ik een issue het het inlezen van deze velden als datum/tijd. Ik ben er niet aan toe gekomen om dit op te lossen en het is vervolgens van de radar gevallen. Een pull request is welkom.
De [documentatie](http://www.gdal.org/drv_gml.html) van de OGR GML-driver toont zelf geen voorbeeld me datum/tijd.

**Comment by skinkie** [comment]
Maak mij maar verantwoordelijk voor dit incident. Zoek het wel uit.

**Comment by fsteggink** [comment]
Thanks

**Comment by fsteggink** [comment]
Hoi Stefan, zal ik het issue gewoon afsluiten? De stringkolommen worden alleen in tijdelijke tabellen gebruikt. Bij het aanmaken van de definitieve tabellen in create-final-tables-v2.1.1.sql cast ik ze wel naar date of timestamp. Hetzelfde doe ik met het veld inonderzoek en andere velden zoals xxxoptalud naar boolean.

**Comment by skinkie** [comment]
Dan sluit ik het wel.
