### ISSUE TITLE
Deduplicatie-script wordt waarschijnlijk niet uitgevoerd bij de BGT

### ISSUE THREAD

**Issue by fsteggink** [nlextract/NLExtract#207]
Zojuist bij het schrijven van een antwoord voor issue #205 viel me op dat de deduplicatie op de definitieve BGT-tabellen (bijv. bak_2d) wordt uitgevoerd, maar op dat moment zijn alleen de tijdelijke tabellen (bijv. bak_2d_tmp) gevuld.

**Comment by fsteggink** [comment]
Inderdaad. De _tmp-tabellen die voor 2d en kruinlijn worden gebruikt, moeten worden gededupliceerd.
Issue gefixed tegelijk met #212.

**Comment by justb4** [comment]
Ok bedankt, alleen vraag: is het door het downloaden van blokken dat je altijd duplicate features krijgt (voor de features die in meer dan 1 blok liggen)? Daarom waren er (dacht voor BRT Top10NL) toch ook de downloads per featuretype? Maar goed ook in Top10NL deden we de-duplicatie...
