### ISSUE TITLE
Crash bij BGT verwerking

### ISSUE THREAD

**Issue by justb4** [nlextract/NLExtract#211]
Waar ligt dit aan? ``max_features`` (20000) ?

@fsteggink : Just, ik heb het idee dat het terugzetten van max features niks oplevert. Dit had met de XSLT te maken (op Windows) en de crash treedt nu op wanneer ogr2ogr wordt uitgevoerd. Ik denk eerder dat er in Stetl (XmlElementReader of elders) nog teveel zaken in het geheugen blijven zitten. Ik weet niet of ik het ergens in een mail heb gezegd, maar ik had nog het vermoeden dat mijn fix nog niet compleet was. Ik weet niet meer precies waar mijn gevoel op gebaseerd was. Waarschijnlijk dat het geheugengebruik bij het verwerken van één XML bestand toch nog gestaag bleef toenemen en dat er een limiet zit aan het aantal GML features. Bijv. de 500000+ wegdelen in blok 48. Daarom zat ik eraan te denken om kleinere blokken te downloaden.

Just: Volgens mij maakt de grootte van het input GML bestand niet uit: er wordt streaming geparsed en via de XMLAssembler nieuwe GML docs samengesteld. Bestand wordt dus opgeknipt n.a.v. max_features. De opgeknipte bestanden worden op disk gesaved en gevoed aan ogr2ogr. Die draait in eigen geheugen/proces.

@fsteggink : Ik denk dat het juist wel uitmaakt. Ieder GML feature wordt namelijk gekopieerd naar een ander XML document. Als het geheugen van dit feature niet wordt vrijgegeven zolang het "moederdocument" nog wordt verwerkt, hoopt dit zich op. In de ideale situatie zal het natuurlijk niet uitmaken.

Just: Ook de ogr2ogr kunnen mogelijk getweaked:
``options = -append -gt 65536 {multi_opts} --config PG_USE_COPY NO``
-gt 65536 "group n features per transaction.."  dat getal is ook wel hoog. PG_USE_COPY NO ? COPY is veel efficienter (of werkte dat niet.)
Ik heb ooit NLExtract BAG geoptimaliseerd met COPY...

@fsteggink : Als maxfeatures onder de 65536 ligt, maakt dit niet uit. Wel interessant om uit te zoeken of dit te optimaliseren is, alhoewel de bulk van de tijd volgens mij in het maken van het afgeleide GML document zit. Idem voor copy. Nog uit te zoeken m.b.v. profiling. Ik heb afgelopen jaar ervaring opgedaan met profiling van Python-scripts.

@fsteggink : Eerst de optie met 32x32 tiles doorvoeren.
De suggesties die jij noemt voor Stetl lijken me zinvol. Zelf zie ik
profiling als een hogere prioriteit. Zowel v.w.b. geheugen als
performance, omdat daar zich pijnplekken lijken te vormen. De BGT moet
toch wel sneller dan een dag te laden zijn? OK, een paar uur gaat er af
van de download en het genereren van de dump, maar toch...

Just: Jazeker, we hebben ook teveel disk-io stappen: 2x m.i.: uit .zip en voor ogr2ogr en COPY scheelt ook, optimalisaties:

- direct uit .zip file lezen (zie bagfilereader.py) in Input
- geen ogr2ogr proces maar via OGR-API (class OgrOutput)
- COPY ipv INSERT

Dat scheelt 2 temporary files. Ik heb met dergelijke stappen destijds NLExtract BAG 3x zo snel gemaakt. Daar is limitatie opbouw intern BAG object model (en multithreading).

@fsteggink : Klinkt veelbelovend

Just:  De reden voor ogr2ogr als Exec proces was dat het mij nog niet gelukt was om via Unix Pipe naar ``ogr2ogr`` te streamen zoals bij ``Ogr2OgrInput``...

Frank: Wat mij betreft alleen een optie wanneer we de huidige workflow voor Windows intact laten.

**Comment by jwva** [comment]
Ik zie dat de BGT dump van 4 februari succesvol is aangemaakt. http://data.nlextract.nl/bgt/postgis/
Bedankt! Wat bleek nu doorslaggevend te zijn? Kleinere km2-blokken? Maxfeatures?

**Comment by fsteggink** [comment]
De kleinere km-blokken (32x32) was de doorslag. Dit duidt sterk op onderliggende geheugenissues bij het streaming verwerken. Pas wanneer het brondocument wordt vrijgegeven, wordt al het geheugen opgeruimd. Bij 64x64 blokken wordt de grens dat het voor de server teveel wordt (teveel geheugen in gebruik) overschreden.

**Comment by fsteggink** [comment]
oops, nog niet sluiten :)

**Comment by justb4** [comment]
Ha, ik ben er nog niet van overtuigd (dat het aan de blokken-grootte ligt). Wat Stetl betreft mag een input file in de GBs zijn,...Zie mijn opmerkingen in eerste stuk en m.n. tweaken featurecount en `ogr2ogr` `-gt 65536`. Maar goed, ik zou het moeten uitproberen.

**Comment by marcovalstar** [comment]
Ik weet niet of dit de juiste plek is om een aantwoord te krijgen maar ik probeer het toch maar.
Ik heb nml de BGT dump gedownload (bgt-20170516.dmp) van http://data.nlextract.nl/bgt/postgis/
Deze probeer ik te restoren in postgresql 9.6.3 in een nieuw aangemaakte database ‘bgt” ik krijg dit echter niet voor elkaar.
Het restore proces komt steeds met de volgende meldingen (het begin maar dit gaat steeds door)

C:\PostgreSQL96\pg96\bin\pg_restore.exe --host localhost --port 5432 --username "postgres" --dbname "bgt" --role "kademo" --no-password  --verbose "D:\Backup\bgt-20170516.dmp"
pg_restore: connecting to database for restore
pg_restore: creating SCHEMA "latest"
pg_restore: creating TABLE "latest.bak_2d"
pg_restore: [archiver (db)] Error while PROCESSING TOC:
pg_restore: [archiver (db)] Error from TOC entry 176; 1259 983948088 TABLE bak_2d kademo
pg_restore: [archiver (db)] could not execute query: ERROR:  type "public.geometry" does not exist
LINE 3:     wkb_geometry public.geometry(Point,28992),
                         ^
    Command was: CREATE TABLE bak_2d (
    ogc_fid integer NOT NULL,
    wkb_geometry public.geometry(Point,28992),
    namespace character v...
pg_restore: [archiver (db)] could not execute query: ERROR:  relation "bak_2d" does not exist
    Command was: ALTER TABLE bak_2d OWNER TO kademo;

pg_restore: creating VIEW "latest.bak_2dactueel"
pg_restore: [archiver (db)] Error from TOC entry 177; 1259 983948100 VIEW bak_2dactueel kademo
pg_restore: [archiver (db)] could not execute query: ERROR:  relation "bak_2d" does not exist
LINE 2: ...us_status, bak_2d.bgt_type, bak_2d.plus_type FROM bak_2d WHE...

Zoals je kunt zien dat er query’s niet bestaan maar deze moet de dump toch zelf aan `maken?
Weet iemand wat ik niet goed doe?

Een oudere versie heb al wel eens kunnen importeren in PostgreSQL 9.2 maar deze was nog niet zo compleet.

Graag hoor ik of iemand mij verder kan helpen.
Bij voorbaat dank.
Groet Marco

**Comment by justb4** [comment]
@marcovalstar nu zie ik wat je issue is: dit is niet gerelateerd aan probleem in issue #211 (gaat over verwerking): PostGIS is vrijwel zeker niet geactiveerd in je database. Staat in handleiding o.a. voor BAG: http://docs.nlextract.nl/en/latest/instructie-win-gui.html#bag-create-database
PostGIS moet geinstalleerd zijn en ook geactiveerd worden bij aanmaken database.

**Comment by marcovalstar** [comment]
Helemaal top was inderdaad de oorzaak.
bedankt

**Comment by fsteggink** [comment]
Voor het geheugenissue heb ik een PR bij Stetl ingediend: https://github.com/geopython/stetl/pull/57
Ik ga delen van de BGT inladen, o.b.v. het volledige extract.

**Comment by justb4** [comment]
Is toch opgelost? Heropen indien niet.
