### ISSUE TITLE
Laatste NLExtract BGT bevat duplicate objecten op bepaalde gridlijnen

### ISSUE THREAD

**Issue by HansvanderMeij** [nlextract/NLExtract#212]
Bij toeval door een transparante instelling wat dubbele BGT-objecten ontdekt en uiteindelijk bleek dit een complete band van west naar oost te zijn.  Uiteindelijk ook meerdere west-oost en ook noord-zuid banden ontdekt en na wat inzoomen  geconcludeerd dat het alleen gaat om objecten die op bepaalde x-lijnen en y-lijnen liggen met een onderlinge interval van 32 km.

Het gaat om BGT-objecten die exact op de volgende x-waarden liggen:  28.000 - 60.000 - 92.000 - 124.000 - 156.000 - 188.000 - 220.000 - 252.000
En tevens op de volgende y-waarden: 328.000 - 360.000 - 392.000 - 424.000 - 456.000 - 488.000 - 520.000 - 552.000 - 584.000 - 616.000

Vermoeden is dat het iets te maken heeft met de downloadgrootte uit PDOK en het niet functioneren van het deduplicatie-script.

**Comment by fsteggink** [comment]
Ik kan het issue op mijn eigen laptop reproduceren. Gek genoeg niet met het BRK-script, dat sinds vandaag gebruik maakt van dezelfde 32x32 km blokken. Later verder induiken...

**Comment by fsteggink** [comment]
Hmm, waarschijnlijke oorzaak: #207
