### ISSUE TITLE
BRK ETL fixen voor nieuwe PDOK Downloads per 1.1.17

### ISSUE THREAD

**Issue by justb4** [nlextract/NLExtract#213]
is in feite al opgelost door @fsteggink, maar om dit issue om werk zichtbaar te maken en evt verdere fixes in Milestone 1.3.0.

Op te lossen was:

- download is nu in "blokken" 32x32 of 64x64 km (ipv Provincies)
- hierdoor (blokken) moeten duplicaties opgelost

**Comment by fsteggink** [comment]
Duplicate van #204, die ik al afgesloten heb, maar niet aan een milestone gekoppeld.
Gelijk maar sluiten?
