### ISSUE TITLE
De-duplicatie BGT resultaat werkt niet goed

### ISSUE THREAD

**Issue by HansvanderMeij** [nlextract/NLExtract#214]
Het recent doorgevoerde de-duplicatiescript (ten behoeve van de dubbele BGT-objecten op de gridlijnen van de downloadgebieden) heeft een ongewenste bijwerking, omdat er bij gemuteerde objecten de actuele versie wordt verwijderd en alleen de historische blijft staan.  Dit omdat er blijkbaar alleen wordt gecontroleerd op een dubbele waarde van het lokaalID.  Een extra controle op attribuut 'eindregistratie' (die niet NULL mag zijn) geeft een beter resultaat.

**Comment by fsteggink** [comment]
Nog niet gereproduceerd, maar dit is ongetwijfeld een bug. Het dedupliceren gebeurt o.b.v. lokaal ID. Ik zal ook tijdstipRegistratie of eindRegistratie hierin moeten betrekken.
