### ISSUE TITLE
Gebruiksdoel toevoegen aan tabel verblijfsobject met geometrie?

### ISSUE THREAD

**Issue by HansvanderMeij** [nlextract/NLExtract#215]
Eén van de meest interessante attributen van een verblijfsobject betreft het gebruiksdoel. Dit geeft voor ruimtelijke analyses duidelijk toegevoegde waarde als dit opgenomen is bij verblijfsobjecten met geometrie.
Helaas is dit nu nog niet het geval en dient er via een omslachtige bewerking gebruik te worden gemaakt van de administratieve tabel 'verblijfsobjectgebruiksdoel' waarin staat aangegeven welke gebruiksdoelen bij een verblijfsobject van toepassing kunnen zijn. 
In hoeverre is het realiseerbaar om aan de geometrische tabel(len) 'verblijfsobject' direct het gebruiksdoel toe te voegen?  Bijvoorbeeld beperkt tot maximaal drie attributen (gebruiksdoel 1, 2 en 3)?

**Comment by XtheOne** [comment]
Zie issue 218 welke deze mogelijkheid bied.

**Comment by justb4** [comment]
Dit issue sluiten omdat deze door #218 vervuld gaat worden.
