### ISSUE TITLE
extra velden BAG adres tabel en in CSV dump

### ISSUE THREAD

**Issue by XtheOne** [nlextract/NLExtract#218]
Als aanvulling op nlextract adres-tabel.sql / adres2csv.sql wil ik mijn adres-tabel-full.sql / adres-full2csv.sql scripts doneren als dank.

**Comment by justb4** [comment]
Top! Denk goed te vermelden dat voorstel deze bestanden beslaat:
SQL:
https://github.com/XtheOne/NLExtract/blob/master/bag/db/script/adres-tabel-full.sql
en CSV dump:
https://github.com/XtheOne/NLExtract/blob/master/bag/db/script/adres-full2csv.sql

**Comment by justb4** [comment]
Twee vragen: 

- een VBO kan soms (plm 4000 keren meen ik) verdeeld zijn over meerdere Panden, hoe gaat script hiermee om?
- een VBO kan meerdere gebruiksdoelen hebben, helaas hoeft de eerste niet het primaire gebruiksdoel te zijn, hoe gaat script hiermee om?

**Comment by XtheOne** [comment]
Vraag 1, ben ik niet echt tegen gekomen. Ik denk dat dan meerdere regels van de VBO gedumpt worden met de gerelateerde panden. Een paar adressen waar dit voor opgaat zou nodig zijn voor een testcase.
Vraag 2, Gebruiksdoelen worden gesorteerd weergegeven in de gegroepeerde kolom, er is dus geen indicatie van de primaire functie. Zover ik weet heft de BAG geen primaire indicatie voor het gebruik van een VBO.

**Comment by justb4** [comment]
On 23-05-17 11:28, Michel wrote:
> Vraag 1, ben ik niet echt tegen gekomen. Ik denk dat dan meerdere regels
> van de VBO gedumpt worden met de gerelateerde panden. Een paar adressen
> waar dit voor opgaat zou nodig zijn voor een testcase.
Komt door N-M relatie VBO-PND. Zijn er ook niet veel, je zou dan evt 
dubbele adressen zien, evt met query te checken

> Vraag 2, Gebruiksdoelen worden gesorteerd weergegeven in de gegroepeerde
> kolom, er is dus geen indicatie van de primaire functie. Zover ik weet
> heft de BAG geen primaire indicatie voor het gebruik van een VBO.
Ok, zag dit ook later:

`ARRAY_TO_STRING(ARRAY_AGG(d.gebruiksdoelverblijfsobject ORDER BY 
gebruiksdoelverblijfsobject), ', ') AS verblijfsobjectgebruiksdoel,`

**Comment by XtheOne** [comment]
Vraag 1, Heb net de aanvulling met oppervlakte getest en gelijk gekeken naar dubbele VBO's / Pand
Ik krijg regels met gelijke VBO id en verschillende pand id onder elkaar.
Een optie is om ook te groeperen op VBO id waar meerdere pandid's in de pandid kolom komen te staan.
Of dit handig is voor verdere verwerking...

**Comment by justb4** [comment]
Ik zou de *"gelijke VBO id en verschillende pand id"* maar zo laten, geen meerdere `pandid`'s in kolom. Het zijn uitzonderingen en meen ik geen "standaard" woonpanden, heb weleens begrepen bijv militaire gebouwen.

**Comment by XtheOne** [comment]
Ook hier oppervlakteverblijfsobject toegevoegd.
Snel getest, lijkt goed. Later uitgebreid testen.

**Comment by justb4** [comment]
Ook getest in standaard BAG extract/dump setup op `data.nlextract.nl`: met BAG XML van Amstelveen (weliswaar uit 2011). Eerste test lijkt ook goed. Oppervlakte van mijn PND VBO klopt :-). Anderen zijn vaak `999999` m2 maar zit in brondata. Zie resultaat:
in tabel
![bagaveen-full-table](https://cloud.githubusercontent.com/assets/582630/26371927/8c0e91b8-3ffc-11e7-9528-8a71d6caea78.jpg)

en als CSV
http://data.nlextract.nl/bag/csv/bag-adressen-amstelveen-full.csv.zip

**Comment by XtheOne** [comment]
Regels toegevoegd aan het export script om bij ID velden voorloop nullen toe te kunnen voegen.

**Comment by justb4** [comment]
On 01-06-17 10:14, Michel wrote:
> Regels toegevoegd aan het export script om bij ID velden voorloop nullen
> toe te kunnen voegen.

Ok, in de toekomst via issue #108 gaan strings (met voorloopnullen) weer 
gebruikt worden. Er is vraag naar en is in lijn met filosofie 
NLExtract-BAG: de BAG as-is inlezen in PostGIS zonder 
interpretatie/conversie velden. Maar dat komt tzt.

**Comment by justb4** [comment]
Wat mij betreft laten we "adres-full" CSV de default worden en daarnaast een [ACN-achtige](https://www.kadaster.nl/documents/20838/88047/Voorbeeld+Adresco%C3%B6rdinaten+Nederland/c07631b2-d08a-46bc-bde6-7c535e55480a) "adres-minimal" (Gemeente,Woonplaats,Straatnaam,Postcode,Huisnummer,Huisletter,Toevoeging,X,Y,lat,lon) kunnen genereren.

**Comment by XtheOne** [comment]
Dit doen met een extra \COPY regel waar alleen die velden in staan?
En welke houden we standard aan? (-- niet als commentaar regel?

**Comment by XtheOne** [comment]
Dit is natuurlijk toe te voegen met indexen. Dan kun je ook bevragen in welke wijk/buurt een adres ligt of een lijst exporteren van adressen in een wijk/buurt.
Lijkt me wel dat dit dan standaard in de BAG dump moet zitten, anders aparte scripts en uitleg hoe je de CBS data toevoegt aan de database.

**Comment by justb4** [comment]
@XtheOne @fsteggink Als test voor BAG aug de CSV full voor heel NL gegenereerd:
http://data.nlextract.nl/bag/csv/
Moest paar zaken wijzigen, bijv output locatie `.csv` en `WHERE` clause voor 'Groningen' weghalen. Zit ook nog niet in PostGIS dump, tabel adres-full via SQL later toegevoegd.

Nog checken en wat mij betreft Pull Request, dan doe ik verdere aanpassing en wordt `full` iedere maand meegenomen.

**Comment by XtheOne** [comment]
Ben weer terug van vakantie.
Ja, zag dat ik de regel die ik zelf gebruik nog actief had staan. Aangepast.
Afgezien van documentatie is het wat mij betreft klaar.

**Comment by justb4** [comment]
Kunnen we sluiten, heropen als er nog/toch probleem is.
