### ISSUE TITLE
geocodeer geocoderen van CSV bestanden

### ISSUE THREAD

**Issue by XtheOne** [nlextract/NLExtract#219]
Als aanvulling op nlextract geocode-tabellen.sql wil ik mijn geocode-tabellen.sql / GeoCode-pc-hn-hl-tv.py / GeoCode-pc-hn-hl-tv.py scripts doneren als dank.
Hier moet nog wel wat documentatie bij lijkt me.

**Comment by justb4** [comment]
Top! Goed te vermelden dat scripts hier staan:

https://github.com/XtheOne/NLExtract/tree/master/bag/src/geocode

**Comment by XtheOne** [comment]
Ik heb nog een aanvulling in stash staan zag ik.
Veld oppervlakteverblijfsobject is daar in toegevoegd. Voor mij niet een heel belangrijk veld, maar kan het nog wel toevoegen als dit wenselijk is.

**Comment by justb4** [comment]
Ja VBO opp. wordt ook veel gevraagd. Je bedoelt dat deze wel in "CSV full" staat, maar nog niet met geocoder wordt opgenomen? Of hoort opmerking bij issue #218 ?

**Comment by XtheOne** [comment]
Dit gaat voor beide issues op, het zit er nu niet in.
Ga ze nu uit de stash halen en testen.

**Comment by XtheOne** [comment]
oppervlakteverblijfsobject toegevoegd.
Snel getest, lijkt goed. Later uitgebreid testen.

**Comment by XtheOne** [comment]
Ook hier oppervlakteverblijfsobject toegevoegd.
Snel getest, lijkt goed. Later uitgebreid testen.

**Comment by XtheOne** [comment]
Met een unittest er bij lijkt mij dit klaar. Issue gesloten.
