### ISSUE TITLE
Volledig extract BGT/BRK gebruiken ipv tiles

### ISSUE THREAD

**Issue by fsteggink** [nlextract/NLExtract#221]
Voor PDOK zijn er sinds geruime tijd extracts van heel Nederland beschikbaar voor de [BGT](https://downloads.pdok.nl/service/cache/bgt-citygml-nl-nopbp.zip) en [BRK](https://www.pdok.nl/download/service/cache/kadastralekaartv3-gml-nl-nohist.zip). De download is stabieler geworden.

Ook de HTTP Range-header wordt ondersteund, waardoor we kleinere chunks zouden kunnen downloaden, zodat na een download van 3 uur de download niet vanwege een netwerkhik opeens corrupt geraakt blijkt te zijn.

**Comment by justb4** [comment]
Kunnen we toch sluiten? Is al gedaan m.i. Heropen indien toch nodig.
