### ISSUE TITLE
CURVEPOLYGON in BGT-dump

### ISSUE THREAD

**Issue by arjennienhuis** [nlextract/NLExtract#222]
Ik zie dat er in de BGT-dump geen curves zitten, maar in de GML-bestanden wel. Waarom is dat?

**Comment by fsteggink** [comment]
Bedankt voor het melden. Ik heb een testgeval nagekeken, begroeid terreindeel met id G0599.16fca6c773c516560e050210a7e247d7

Bij het inlezen in PostGIS wordt ogr2ogr gebruikt (onderdeel van GDAL). Dit is verantwoordelijk voor het stroken van de arcs. Op de server waarop we de dumps genereren, gebruiken we nog GDAL 1.11.2. Hoog tijd om te upgraden. GDAL 2.0 zou wel arcs moeten teruggeven: [http://www.gdal.org/drv_gml.html](http://www.gdal.org/drv_gml.html). Ik was sowieso van plan om meer gebruik te maken van de mogelijkheden van GDAL 2.0.

**Comment by fsteggink** [comment]
Afgelopen woensdag en vandaag ben ik hiermee bezig geweest. Nu ondersteunt BGT-Extract wel curves, maar het is nog niet perfect. Op data.nlextract.nl staat nog geen kant-en-klare dump.

**Comment by fsteggink** [comment]
Eergisteravond heb ik een nieuwe dump gemaakt. Gisteren op data.nlextract.nl gezet. Alle vlakken zijn nu curvepolygons. Willem Hoffmans, die ook tegen dit issue was aangelopen, heeft al bevestigd dat enkele van zijn testgevallen er nu goed uitzien. Ook heb ik nog geen fouten gezien die hieraan te wijten zijn. Verder bevat het feature dat ik hier noemde nu ook een circularstring als onderdeel van de grens van de curvepolygon:  CURVEPOLYGON(COMPOUNDCURVE((95652.64 433919.07,95652.07 433919.03,95651.43 433920.93,95648.86 433919.84,95648.13 433916.19,95649.358 433913.654),CIRCULARSTRING(95649.358 433913.654,95649.76 433913.8,95650.58 433914.24),CIRCULARSTRING(95650.58 433914.24,95651.55 433915.3,95652.22 433916.48),CIRCULARSTRING(95652.22 433916.48,95652.56 433917.72,95652.64 433919.07))).
Wat mij betreft, kan dit issue worden gesloten.
