### ISSUE TITLE
Timestamp with timezone in postgres

### ISSUE THREAD

**Issue by arjennienhuis** [nlextract/NLExtract#223]
Volgens mij is van alle tijden de tijdzone bekend. Dan zouden de kolommen timestamptz moeten zijn. Ze zijn nu allemaal timestamp zonder timezone.

In postgres is een timestamp zonder timezone een soort geometry zonder srid.

**Comment by fsteggink** [comment]
Goed punt. Dit is i.i.g. bij de BGT zo. Bij de BRK laten we trouwens de tijden als string staan. Dat moet beter kunnen. Dit heeft er ondermeer mee te maken dat GDAL/OGR moeite heeft (had?) met het omzetten van datum- en timestamp-velden in de GML naar velden van het juiste type in PostgreSQL.

**Comment by borrob** [comment]
Voor het BAG heb ik de wijzigingen klaar staan. Vraag: de tabeldefinities veranderen (van zonder naar mét time zone), moet de schema-versie dan ook opgehoogd worden ?https://github.com/nlextract/NLExtract/blob/568a45e4145362c72f47216291a1bee1bad955da/bag/db/script/bag-db.sql#L21

**Comment by justb4** [comment]
@borrob Bedankt! Ja hoog schema-versie maar op. Idd, `timestamptz` heeft voorkeur. Belangrijker, hoewel in BAG datums belangrijker zijn dan uren, minuten, is hoe bij inlezen de juiste conversies worden gedaan. Geen idee eigenlijk hoe in de BAG bijv `begindatumtijdvakgeldigheid` qua tijdzone is. In ieder geval [wordt bij inlezen een ISO 8601 string gevormd](https://github.com/nlextract/NLExtract/blob/master/bag/src/bagattribuut.py#L317), maar zonder TZ, bijv `1999-01-08 04:05:06.78`. Doe je daar ook iets mee? Je kan anders wel een PR aanmaken voor code review.

**Comment by borrob** [comment]
Thanx. Ik open zo een pull request. Ik heb aangenomen dat de aangeleverde gegevens in de Nederlandse tijdzone (Europe/Amsterdam) zijn gebeurd. Bij het inlezen wordt de db-connectie op die tijdzone ingesteld en daarmee krijgen de datumtijd-velden dat automatisch toebedeeld bij het inlezen. Dat betekent UTC+1 voor wintertijd en UTC+2 voor zomertijd.

Overigens begrijp ik uit pagina 8 van de [beschrijving van het BAG-koppelvlak](https://www.kadaster.nl/documents/20838/87954/BAG+Bevragen+koppelvlak+versie+2.1/2d92abea-bb45-2e52-6fd5-ae5837417f17) dat: 

> Tijdvakgeldigheid wordt op diverse plekken hergebruikt. Het gaat hier in principe om datums. Het type lijkt echter op een datum-tijd, maar moet geïnterpreteerd worden als een datum. Het tijd-deel van de datum is om meerdere voorkomens op één dag uniek van elkaar te kunnen onderscheiden. Dit moet geïnterpreteerd worden als een volgnummer binnen de dag. De hoogste c.q. laatste is degene die telt bij een bevraging op deze dag (actueel of peildatum).

Hieruit haal ik dat het dus niet zo zeer om een specifieke tijd gaat, maar meer om een volgorde. Ik zal kijken wat ik nog voor de BGT en de andere datasets kan doen.

**Comment by fsteggink** [comment]
Issue aan mezelf toegevoegd, om dit voor de TOP10- en overige BRT-extracten en BRK-extract na te kijken / fixen.

**Comment by borrob** [comment]
Vanwege de discussie op #238  realiseer ik me dat ``LOCALTIMESTAMP`` in de actueel-views ([NLExtract/bag/db/script/bag-view-actueel-bestaand.sql](NLExtract/bag/db/script/bag-view-actueel-bestaand.sql)) nog aangepast moet worden naar ``now()``. Het lijkt me goed om de discussie in die draad eerst af te wachten of er wél of geen tijdzones gehanteerd gaan worden voordat we eventueel extra werk moeten terugdraaien.

**Comment by fsteggink** [comment]
@borrob: Just en ik hebben beide besloten om je aanpassing intact te laten, dus mocht je in de gelegenheid zijn om hiervoor nog een PR te maken, dan zou dat heel fijn zijn.
Ik ga nu aan de slag met de andere hierboven genoemde extracten. Eindelijk tijd :tada:

**Comment by fsteggink** [comment]
Voor de BRK zie PR #242 .

**Comment by fsteggink** [comment]
De BRT-features hebben alleen datums. TOP50NL en TOP100NL bevatten wel data met tijdstippen, nl. objectbegintijd en objecteindtijd. Het laatste attribuut is altijd leeg, omdat de BRT alleen actuele data bevat. Bij objectbegintijd is het tijdstip altijd 00:00:00.000. Dat is logisch, want bij TOP10NL is helemaal geen tijdstip meerbeschikbaar en dit lijkt een gevolg van een verouderd datamodel. Zie ook de versienummers. TOP50 en 100 zitten op v1.1 en de rest op v1.2.

Ik ga het issue afsluiten, want in alle datasets waar dit van toepassing is, hebben we een tijdzone toegevoegd.
