### ISSUE TITLE
error on importing Top10NL

### ISSUE THREAD

**Issue by VNuhaan** [nlextract/NLExtract#227]
I get an error when importing Top10NL into PostgreSQL 10, see schreenshot
![import probleem](https://user-images.githubusercontent.com/5813554/31314704-bd6d6942-ac07-11e7-8cf9-afcae7d263ce.png)

**Comment by justb4** [comment]
Het inlezen is op zich goed gegaan. Alleen bij "postprocessing" faalt het bijwerken van "multiattributen" dwz velden die "multivalued", meerdere waarden. Lijkt alsof die bij inlezen naar "arrays" zijn gemapped. Dit is een setting in je `etl/options/<hostname>.args`, bijv

```
# OPTION: attribuut waarden bijv typeWeg die meerdere keren in XML voorkomen, wat daarmee te doen
# Zie ogr2ogr opties
# May use: these options
# multi_opts=-splitlistfields -maxsubfields 1
# multi_opts=-splitlistfields
multi_opts=-fieldTypeToString StringList
```

Meestal mappen we een `GFS StringList` naar PG `String`, omdat meeste software niet met array-types kan omgaan. Kijk anders in bijv je tabel `gebouw_vlak` naar PG-type van  `typegebouw`. Normaal `character varying`. Zal waarsch bij jou een array type zijn.

**Comment by VNuhaan** [comment]
Ik heb 'mult_opts=' (leeg), dan krijg ik array type. Dan werkt de "postprocessing" zeker niet? Is dit belangrijk of kan ik wat aanpassen zodat ik de foutmeling niet meer krijg?

**Comment by justb4** [comment]
Probeer: `multi_opts=-fieldTypeToString StringList` (maakt string velden ipv array) en alles opnieuw draaien.

**Comment by VNuhaan** [comment]
Bedankt, het werkt

**Comment by justb4** [comment]
Mooi, dan kunnen we deze sluiten!
