### ISSUE TITLE
Voorstel om importeer snelheid te verhogen

### ISSUE THREAD

**Issue by VNuhaan** [nlextract/NLExtract#235]
Met het zoeken naar de oplossing voor missende objecten heb ik wat 'gespeeld' met GDAL. Inmiddels kan ik melden dat ik met succes Top10NL en BGT erg snel kan importeren. Wel wordt de data dan niet meer per geometrie opgeslagen, maar als objecten met meerdere geometrien.

Het importeren van BGT duurde met 32 uur, nu met de pure GDAL oplossing nog maar 3 uur en 45 minuten. Daarbij was het geheugen gebruik niet hoger gekomen dan 15MB.

Ik heb geen code die ik kan delen omdat ik het in LabVIEW geschreven heb. Wel kan ik aangeven wat ik heb gedaan.

Importeer stappenplan:
1. unzip een gml bestand
2. bepaal d.m.v. ogrinfo het aantal objecten dat in de gml bevinden. Dit staat in de door ogrinfo gegenereerde gfs.
3. Verander of overschrijf de gfs van stap 2 met een aangepast gfs. Hier komt het punt van meerdere geometrien per object. Zorg er ook voor dat het aantal objecten wordt genoemt, want dat zorgt voor een flinke importeer snelheidsverhoging. Geef ook alleen maar objecten op die in de gml voorkomen. Je kan ook bij objecten het aantal 0 opgeven, maar dit zorgt voor onnodige vertraging. 
4. importeer de gml met ogr2ogr. Met de 'gewone' gml importeer methode, niet de gmlas methode, die werkt niet goed.
5. herhaal stap 1 t/m 4 met alle gml bestanden in de database export.

Wat ik nog niet kan is het samenvoegen van geometrieen zoals NLExtract dat doe. Dit is vooral zichtbaar in Top10NL, die noemt bijvoorbeeld polygonen en multipolygonen als aparte geometrien, dus worden dit in postgresql aparte kolommen. Ik ben nog bezig om dit te onderzoeken of dit anders kan. Wellicht dat ik nog iets met view's kan doen.

**Comment by fsteggink** [comment]
Hoi Vincent,

Dat klinkt erg goed! Met name het uitvoeren van de XSLT om de GML features in meerdere objecttypen op te splitsen neemt veel tijd in beslag, met in het kielzog het opsplitsen van de GML, omdat o.a. op Windows tegen geheugenbeperkingen wordt aangelopen. Het staat al een tijd op mijn programma om dit aan te passen, mede geïnspireerd door de BGT import plugin van Marco Duiker in QGIS. Met GDAL 2.0 is het mogelijk om meerdere geometriekolommen per feature te gebruiken en het is altijd beter om zo min mogelijk handelingen daaromheen uit te voeren. Zie de BRK voor een voorbeeld met meerdere geometrieën (Perceel bevat grens en centroidepunt.)

De tip van OGRInfo om de objecten te tellen is een goede. Ik heb me überhaupt nog niet gerealiseerd dat dit eventueel van invloed op de snelheid zou kunen zijn. Waardevolle informatie. Verder deel ik je mening over de GmlAs driver. Een paar maanden geleden zag ik bij iemand anders het resultaat in PostGIS, maar dit was zo complex, dat er geen touw aan vast te knopen viel.

Polygonen vs multipolygonen zijn bij de TOP10NL van belang bij de gebieden (functioneel, geografisch en registratief). Vlakken worden nu geïmporteerd met geometrietype 6, dus alles als multipolygon. Dat werkt prima.

Bij het aanpassen van de TOP10NL en BGT import zou ik wel verschillende geometrietypen in verschillende kolommen willen onderbrengen. Het grote voordeel is dat je dan in de database een restrictie op geometrietype (punt, lijn, vlak, etc.) kunt maken, zodat o.a. QGIS bij het laden van de data niet zelf oneindig lang bezig is met het bepalen van het geometrietype. Ik weet niet zeker of dit gaat werken, of dat we hier iets "slims" (en waarschijnlijk wordt het dan trager...) voor moeten verzinnen. Hoe heb jij dit aangepakt? Een nadeel is wel dat je veel geometriekolommen kunt krijgen, bijv. maar liefst vijf bij wegdelen, maar het zij zo.

**Comment by fsteggink** [comment]
E.e.a. is goed in een NLExtract structuur te gieten. Voor het genereren van de GFS van de BGT en TOP10NL, die erg uitgebreid is, heb ik in tools/make-gfs een XSLT-script gemaakt die een template-bestand omzet naar een GFS-bestand. Het template-bestand staat in etl/meta bij TOP10NL, BGT en BRK (en de nieuwe BRT-datasets).

Aan het template-bestand zouden ook de aantallen teogevoegd kunnen worden. Ik neem aan dat dit niet exact hoeft te kloppen, maar dat een benadering goed genoeg is. Ongeveer hetzelfde als wanneer een database een execution plan samenstelt, die afhankelijk is van de cost, die weer afhankelijk is van het aantal records.

Een ander ding om rekening mee te houden is om PG_USE_COPY aan te zetten. Ik heb die een keer uitgezet, omdat dit vreemd genoeg trager leek te zijn, terwijl dat eigenlijk niet zou moeten. Misschien een gevolg van het ontbreken van de aantallen? Dit onderzoek is stil blijven liggen.

Genoeg stof tot nadenken. Een flinke verbetering van de performance achtte ik niet onwaarschijnlijk, maar de BGT in 3 uur en 45 min had ik niet verwacht!

Ik neem aan dat de tijd van 32 uur incl. het ontdubbelscript delete-duplicates-v2.1.1.sql is? Die gaat er sowieso uit. Die was oorspronkelijk nodig, omdat we BGT bloksgewijs moesten inladen vanwege een geheugenissue. Ik heb hem niet gelijk verwijderd, omdat er toch nog dubbele voorkomens leken te zijn. Dit kwam alleen bij vervallen objecten voor. Dit bleek uiteindelijk het gevolg te zijn van een inconsistentie in de BGT standaard. Een voorkomen heeft een tijdstip- en eindregistratie (tijd), alsmede een LV-publicatiedatum. Alleen is er bij het vervallen verklaren van het hele object geen voorkomen meer na het moment van vervallen, maar de LV-publicatiedatum moet wel worden gepubliceerd, vandaar dat is besloten om het laatste voorkomen (met laatste tijdstipregistratie) te verdubbelen.

**Comment by VNuhaan** [comment]
Wat mij nog niet lukt met GDAL maar wat NLExtract wel doet is polygonen en multipoligonen samenvoegen als één kolom van multipoligonen. Ik krijg dus nu alle verschillende geometrien in aparte kolommen. Dit is geen probleem bij QGIS.
GBT heeft een aantal objecten met verschillende geometrieen door elkaar, hier heeft NLExtract ook moeite mee. Dus dit wordt als een geometrie object opgeslagen. QGIS gaat dus helaas zelf de geometrie proberen te bepalen. Wellicht kunnen view's hier ook een oplossing zijn.

Het enige wat ik aangepast heb in zowel BGT als in Top10NL is de transformatie naar google coordinaten. Dit om de data snel te kunnen gebruiken met Mapbox Studio Classic. Anders is deze continu de coordinaten aan het vertalen.

Ik heb bijgevoegd de gfs bestanden die ik heb aangepast om alle geometrieen in verschillende kolemmen te krijgen.
[gfs.zip](https://github.com/nlextract/NLExtract/files/1653557/gfs.zip)
Letop dat de objectaantallen allemaal op 0 staan, deze aanpassen met de ogrinfo aantallen. Objecten die niet voorkomen moet je wissen uit de gfs het gfs bestand. Dit importeerd het snelst.

**Comment by VNuhaan** [comment]
Afgelopen nacht BGT geimporteerd, hierbij de log die ik heb bijgehouden
[BGT import log.txt](https://github.com/nlextract/NLExtract/files/1655108/BGT.import.log.txt)

**Comment by fsteggink** [comment]
Je kunt de GeomPropertyDefn's bij RegistratiefGebied, etc. gewoon vervangen door     <GeometryType>6</GeometryType>. Dat zou moeten werken.

Uitsplitsen geometrieën naar type: views werken, maar zolang de DB user ook leesrechten heeft op de originele tabellen, zal QGIS hier alsnog op wachten. Ik zit zelf te denken om aan NLExtract een post processing SQL script toe te voegen die nieuwe geometriekolommen toevoegt, met een beperking op het geometrietype, en daar de geometrieën uit de kolom van het type Geometry naar toe kopieer. Na afloop kan de oude kolom worden opgeruimd.

Een andere uitdaging zijn features met subfeatures. Dit zijn o.a. de kruinlijnen in de BGT, almede nummeraanduidingen bij panden en openbareruimtelabels. Ik zit in jouw GFS-bestand te kijken. Voor kruinlijnen en nummeraanduidingen gaat dit werken, omdat er maar 1 subfeature per hoofdfeature zal zijn, maar bij openbareruimtelabels wordt per label maar 1 positie ingelezen. Of gaat dit wel goed?

**Comment by VNuhaan** [comment]
Bij RegistartiefGebied kan dat omdat GDAL polygonen dan vertaald naar multipolygonen. Maar zodra er een ander geometrie soort erbij komt zoals bij FunctieoneelGebied kan je het niet meer samenvoegen as een bepaald soort (punt, lijn of vlak). Alleen als een algemeen geometrie object (0) of als geometrycollection (7). Maar dat wilden we toch juist niet?
Justb4 gaf aan om dit met view's op te lossen. Dat wil ik wel proberen.

**Comment by fsteggink** [comment]
Ah ja, dat klopt. Hetzelfde geldt voor GeografischGebied.
Bij views moet je ervoor zorgen dat de brontabel uit zicht van QGIS blijft.

**Comment by fsteggink** [comment]
Vandaag ben ik hiermee aan de slag geweest. Het ijzer smeden wanneer het heet is :) TOP10NL kan bij mij lokaal in 1 uur en 42 minuten geladen worden. Voorheen was het 6 a 8 uur, dacht ik. De BGT zal ook ongetwijfeld sneller gaan. Ik ben dit maar gelijk op de NLExtract server aan het testen.

Een uitgebreide toelichting volgt later. Voor nu zie mijn commits. O.a. GFS-templates en -bestanden en SQL-scripts zijn aangepast.

Bij de BGT een "bijvangst" gedaan. Laatst hoorde ik op de OSGeo.NL borrel dat er mogelijk wat problemen waren bij de NLExtract export van de BGT, nl. dat een deel van de curves gestroked bleken te worden. Dit is inderdaad waar. Ik had nog geen tijd dit uit te zoeken, maar kwam hier "toevallig" achter toen ik de geometrieën van kunstwerkdelen en andere BGT-objecten wilde uitsplitsen naar geometrietype.

Hierover gesproken, ST_CircularString wordt niet omgezet naar ST_CompoundCurve met ST_ForceCurve. Bij kunstwerkdelen, etc. heb ik hier wat omheen moeten werken. Ik kon niet gauw een functie vinden om een compound curve te maken van een circular string, anders dan met ST_GeomFromText en ST_AsText :( Maar goed, het lijkt te werken.

**Comment by fsteggink** [comment]
TODO: TOP50NL etc. ook omzetten. Net vorige week toegevoegd... :(

**Comment by VNuhaan** [comment]
Leuk om te lezen dat het bij jou ook zo snel gaat. Ik kijk uit naar de update van NLExtract.

**Comment by fsteggink** [comment]
Gisteravond heb ik op mijn eigen laptop een import afgestart. Het laden duurde 11 uur. Wel veel langer dan wat jij rapporteerde, maar dit is incl. het uitpakken van de GML en zo. Het is volgens mij wel meer dan 50% sneller, tenminste als ik het vergelijk met de NLExtract server. Het genereren van de definitieve tabellen duurde ongeveer een half uur.

Ik heb het GFS bestand flink op de schop genomen. Ik ben benieuwd in hoeverre dat impact heeft op de laadtijd. Het laden was nog zonder het bepalen van de aantallen. Nu ik het een keer geladen heb, is het interessant om te kijken of het bepalen van de aantallen echt een positieve impact heeft.

**Comment by VNuhaan** [comment]
Mijn 3 uur en 45 minuten was inclusief uitpakken zip (per gml bestand), aanpassen van gfs en importeren in postgis met vertalen van RD naar Google coordinaten (-t_srs epsg:3857). Ik had de gfs van NLExtract zo verbouwd dat de tabel namen geen 2d tovoeging meer hadden en dat de geomerieën zo veel mogelijk in apparte kolomen per type geometrie worden opgeslagen.

Mijn ervaring is dat als je het aantal objecten bepaald en de niet gebruikte opjecten ook niet benoemd in de gfs dat de importeer snelheid flink verbeterd.

**Comment by VNuhaan** [comment]
Ik heb afgelopen weekend top10nl geïmporteerd met de laatse wijzigingen van NLExtract. Bij mij duurde het 3 uur (inclusief vertalen naar Google coördinaten).
Vervolgens heb ik mijn LabVIEW gebaseerde tool laten importeren, deze past de gfs bestanden aan. Het importeren duurde toen nog maar 2 uur en 15 minuten. Een minder grote snelheidswinst dan die van BGT.

**Comment by VNuhaan** [comment]
[update-geoms-bgt_vn.zip](https://github.com/nlextract/NLExtract/files/1684657/update-geoms-bgt_vn.zip)
Ik heb de het bestand 'create-final-tables-v2.1.1.sql' bekeken. Er is nog een aanpassing die gedaan kan worden. Het is mogelijk om COMPOUNDCURVE en CIRCULARSTRING samen te voegen tot een MULTICURVE. Zie bijgesloten bestand hoe ik dat gedaan heb. Dan kom je weer op de drie basis geometrieën uit, vlak, lijn en punt.

**Comment by fsteggink** [comment]
De truc kan inderdaad het niet benoemen van de niet-gebruikte objecten zijn. Ik heb hier nog niet mee geëxperimenteerd. Dit kan makkelijk toegepast worden bij de BGT, omdat de objecttypen per bestand worden opgeslagen. Bij TOP10NL kan dat niet. Bij mijzelf vind ik dat ook niet nodig, want de TOP10NL kan ik in minder dan 2 uur laden :) Maar dit is zonder transformatie naar World Mercator.

Zojuist heb ik het GFS-bestand van de BGT weer aangepast. Eerder deze week ook van TOP10NL. De tabellen bij de BGT hebben geen 2D-suffix meer en bij zowel de BGT als TOP10NL zijn ook de geometrie-attributen nu volledig in het Nederlands.

V.w.b. je aanpassing: ik wil zelf niet switchen tussen "single" geometrie en een multigeometrie. Een compoundcurve en een circularstring blijven in mijn optiek beide "single" curves (geometric primitive). De cast van circular string naar compoundcurve is niet fijn, maar dat ligt aan de implementatie van het geometriemodel in PostGIS, die gebaseerd is op SQL/MM Spatial.

**Comment by VNuhaan** [comment]
Ik ben zelf nog aan het experimenteren met het tekenen van de nieuwe importeer wijze. Zo moet ik alle geometriekollommen herzien in Mapbox Studio Classic. Echter heb ik er geen probleem mee met de 'singel' geometrieën. Ik heb zelfs alles geometrieën gegroepeerd zodat ik weer op vlak, lijn en punt uit kom. Zo heb ik geen geometrie_multivlak, maar gewoon geometrie_vlak. En de compoundcurve en circularstring zijn heb ik samen genomen tot een geometrie_lijn. Met QGIS heb ik al wat data gecontroleerd en dat ziet er goed uit. Ook het samenvoegen van de compoundcurve met sircularstring geeft geen foutmeldingen.

**Comment by fsteggink** [comment]
Het is me na een dagje zwoegen gelukt om NLExtract met Stetl zodanig aan de praat te krijgen dat ik gebruik maak van de feature counts en van één enkele objecttype per bestand. Mijn testbestand kan ik nu in 27 seconden ipv 47 seconden laden!

Dit is met dank aan de split-functionaliteit die Just een aantal maanden heeft gebouwd. De werkwijze is wel ontzettend lelijk en ik heb wat lokale aanpassingen aan Stetl gedaan. E.e.a. moet nog flink opgekalefaterd worden.

**Comment by fsteggink** [comment]
Op de valreep nog een bizarre ontdekking gedaan. Ik wil per se altijd alle tabellen aanmaken. Op het moment dat ik dit nog niet deed, had ik de indruk dat ik de data een stuk sneller dan 27 seconden kon laden. Voor het aanmaken van alle lagen heb ik een dummy.zip bestand met een leeg CityGML document. Die laad ik met ogr2ogr met de volledige GFS. De tijd van 27 seconden is wanneer ik de dummy.zip voor de daadwerkelijke data laad, maar als ik dit omdraai, is mijn testbestand in 16 seconden geladen!

Blijkbaar vindt OGR het nodig om, wanneer een tabel al bestaat, alle data een keer extra te lezen en te checken of dit toch echt geen problemen zal veroorzaken bij het laden. Het kan ook wat anders zijn, maar gezien de duur, verwacht ik wel dat de data nog een keer gelezen wordt.

**Comment by fsteggink** [comment]
Gisteravond heb ik het extract dat ik een paar weken heb gedownload en in 11,5 uur kon laden opnieuw geladen. Het resultaat is verbazingwekkend: het laden zelf was al in 1 uur en 20 minuten klaar, dus meer dan 8 keer zo snel dan de 11 uur voor die tijd!

De postprocessing duurde 28 minuten en is zo goed als ongewijzigd. Vanochtend snel een dump gemaakt als check. Die was ongeveer net zo groot. Verschillen zijn te verklaren door het wijzigen van tabel- en kolomnamen. Hij staat nog niet online.

**Comment by fsteggink** [comment]
Voor de volledigheid zou ik ook nog een keer een dump moeten laden op de oude werkwijze op mijn eigen laptop. Pas dan heb je een goede vergelijking. Of deze aanpassing op de NLExtract server werkend krijgen, maar daar gaat nog wel even wat tijd overheen.

**Comment by VNuhaan** [comment]
Dat is snel.

Over je bizarre ontdekking. Maak je vooraf alle tabellen aan en ga je daarna pas importeren. Of gebruik je bij het importeren een gfs bestand waar alle tabellen in beschreven zijn (ookal gebruik je er maar één)?

Wat ik heb gedaan is niet vooraf de tabbellen aanmaken, maar dit aan org2ogr overgelaten. Ik zal gaan experimenteren met het vooraf aanmaken van de tabbellen om te kijken  of dit sneller werkt.

**Comment by fsteggink** [comment]
Bij het importeren maak ik nu gebruik van een GFS-bestand waar alleen maar de te importeren tabel in staat gespecificeerd. Na afloop importeer ik een dummybestand (leeg CityGML document) tezamen met het originele GFS-bestand. De tabellen die nog niet zijn aangemaakt worden zo aangemaakt. Ik maak de tabellen dus niet vooraf aan.

**Comment by fsteggink** [comment]
Vandaag heb ik wat aanpassingen gedaan. De werkwijze is nog steeds hetzelfde, maar het is een nettere oplossing. Ik leunde o.a. op XML Starlet en een Windows batch file om tijdelijke bestanden op te ruimen. Dat kan natuurlijk niet ;) Ik heb hiervoor in Stetl een nieuw filter gemaakt, nl. het [GfsPreparationFilter](https://github.com/fsteggink/stetl/blob/gfs_preparation_filter/stetl/filters/gfspreparationfilter.py). 

Ik heb net een ontwerpvraag bij Just uitgezet, want een aantal filters die ik een paar weken heb gemaakt, heb ik nu in 1 nieuw filter samengevoegd. Hoezo separation of concerns? 😇 Het zou mooi zijn als we een "subchain" kunnen definiëren en uitvoeren.

Dit issu laat ik nog open, want ik ben nog niet 100% tevreden.

**Comment by fsteggink** [comment]
Ik heb het GfsPreparationFilter verplaatst naar NLExtract zelf: https://github.com/nlextract/NLExtract/tree/bgt-split-gfs/bgt/etl/stetlcomponents
In theorie is het generiek te gebruiken, maar momenteel gebruik ik het alleen voor de BGT.
Mischien ga ik er binnenkort aan de slag, maar eerst ga ik aan de slag met andere zaken. Ik ga dit issue afsluiten als @VNuhaan hiremee akkoord is. Laat me dat s.v.p. weten.

**Comment by fsteggink** [comment]
Hmm, ik moet ook nog even de BRK en TOP10NL checken. Alsmede de overige BRT datasets.

**Comment by fsteggink** [comment]
De BRK gaat wel lukken, omdat ook hier 1 featuretype per bestand in voorkomt. De BRT datasets wordt een uitdaging, omdat featuretypes over meerdere bestanden verdeeld kunnen zijn en een bestand meerdere featuretypes kan bevatten. Ik vraag me af in hoeverre het bepalen van de featurecount wel of juist niet invloed heeft op de performance. Ik wil wel een poging doen, maar gezien de kleinere omvang en de lagere updatefrequentie is het geen groot issue. Het is wel interessant om te weten. ;)

**Comment by fsteggink** [comment]
Ik heb de BRK aangepast (zie PR #241), alsmede TOP10NL, TOP50NL en TOP100NL.
Bij TOP250NL merkte ik geen winst. Dit omdat het maar 1 bestand is, dus ik heb het achterwege gelaten. Bij mij laadt het toch in 20 seconden. Idem voor TOP500NL en TOP1000NL.
Bij TOP50NL en TOP100NL heb ik een verbetering van "slechts" 33% ervaren. Waarschijnlijk vanwege de manier waarop het uitgeleverd wordt. Desondanks mooi dat er winst te behalen is. Bij TOP10NL heb ik het nog niet getest, maar ik verwacht een soortgelijke verbetering.

Het GfsPreparationFilter staat nu hier: https://github.com/nlextract/NLExtract/tree/master/stetlcomponents
In de etl-xxx cmd en sh scripts heb ik het pythonpath hierop aangepast. Dit hoef je niet meer met de hand te zetten.

Ik sluit hierbij het issue.

**Comment by VNuhaan** [comment]
Goed om te lezen wat je allemaal gedaan hebt. Ik zal binnekort je code testen.
Zelf ben ik nog erg aan het stoeien met de geometrietypen. Mapbox Studio Classic kan geen Arc gebaseerde geometrien aan. Dus ik zit met het idee om de geometriekollommen te verdubbelen. Eén kolom voor QGIS (met Arc) en één kolom voor Mapbox (zonder Arc). Ik probeer te voorkomen dat het exporteren in Mapbox traag wordt. Daarom wil ik vooraf alle vertaalslagen gemaakt hebben. Dan denk ik dat het beter is om de geometrien in postgis op te slaan in google coordinaten en als 'gewone' punten, lijnen en vlakken. Maar dit is wellicht iets voor een andere issue.
