### ISSUE TITLE
Linked data als doel

### ISSUE THREAD

**Issue by semanticfire** [nlextract/NLExtract#24]
Ik zou graag bij willen dragen aan de linked data variant hiervan. Ik weet dat e.a. via geonovum straks geinitieerd wordt, maar ik ben van het ongeduldige type.

Ik heb een lokale test draaien waarbij ik zeer plat de PostGIS database met d2r server naar RDF omzet, er moet nog wel e.a. gebeuren om e.a. productie rijp te krijgen.

Is er belangstelling voor om hier bijv. de mapping die nodig is tussen postgis en d2r te hosten ?
Heb overigens geen enkele geo ervaring, maar snap Linked data/ RDF des te beter ;)

Bart

**Comment by reinvantveer** [comment]
Ik denk dat dit issue nu wel gesloten kan worden - het Kadaster heeft zelf initiatieven ontplooid om basisregistraties als linked data aan te bieden (disclaimer: ik was zelf onderdeel van dit initiatief). Deze zijn onder basisregistraties.overheid.nl beschikbaar gekomen.
