### ISSUE TITLE
Report on spelling in BAG addresses

### ISSUE THREAD

**Issue by PanderMusubi** [nlextract/NLExtract#246]
Report on spelling in BAG addresses with PR from work at hackathon.

**Comment by fsteggink** [comment]
@PanderMusubi: Ben je nog van plan iets hiervoor te committen, of zullen we het issue gewoon sluiten? Het is me niet duidelijk wat je precies beoogt.

**Comment by PanderMusubi** [comment]
Deze staat tegenwoordig hier https://github.com/OpenTaal/opentaal-nlextract Heb nog wel een verzoek van een soortgelijke export van andere collecties dan BAG voor analyse spelling, maar dat zijn andere issues.

**Comment by PanderMusubi** [comment]
Zie https://github.com/nlextract/NLExtract/issues/248
