### ISSUE TITLE
 Report on spelling in BGT names

### ISSUE THREAD

**Issue by PanderMusubi** [nlextract/NLExtract#247]
Report on spelling in BGT names with PR based on work from hackathon for BAG.

**Comment by fsteggink** [comment]
@PanderMusubi: Ben je nog van plan iets hiervoor te committen, of zullen we het issue gewoon sluiten? Het is me niet duidelijk wat je precies beoogt. Zie ook de opmerking van Ivo in issue #248.

**Comment by fsteggink** [comment]
Gezien de rapportage die je in #246 noemt denk ik niet dat het onderdeel is van NLExtract. Je kunt een dergelijke rapportage prima in je eigen repo opnemen. Ik ga dit issue dus afsluiten.

**Comment by PanderMusubi** [comment]
Prima
