### ISSUE TITLE
Nieuwe https://nlextract.nl website issues

### ISSUE THREAD

**Issue by justb4** [nlextract/NLExtract#257]
Laten we dit issue gebruiken om editorial issues voor nieuwe https://nlextract.nl website te bundelen (ipv issue per website-issue). Gedane issues kunnen we afvinken, Zie ook https://geoforum.nl/t/nlextract-website-vernieuwd/2112

- [x] Op de downloads pagina verwijzen ze de meeste Brondata links, naar verkeerde pagina’s.
- [ ] Bij de PostGIS dump links: datum verwachten zodat te  zien is wanneer deze vernieuwd zijn.  *JvdB: in ieder geval is aangegeven dat het laatste data is, dynamische links zijn lastig, ivm koppelingen 2 websites*
- [x] Wellicht ook met een linkje naar historische data (vorige dumps). *Link naar archief erbij*
- [ ] Expliciet de "Gallery/toepassingen" als link

**Comment by fsteggink** [comment]
Het spijt me, maar mijn planning zit op dit moment ramvol.

**Comment by justb4** [comment]
Voor stale links: WP Broken Link Checker:
https://www.maketecheasier.com/check-broken-links-wordpress-plugins/

**Comment by justb4** [comment]
Website is nu al bijna 3 jaar in de lucht. Sluiten deze en specifieke issues openen.
