### ISSUE TITLE
Ongeldige Postcodes

### ISSUE THREAD

**Issue by marcojanssen** [nlextract/NLExtract#262]
In de tabel adres staan o.a. de volgende combinatie postcode / stad:

Postcode | Stad
-- | --
1222AB | Bussum
1244PT | Kortenhoef
1363CG | Wervershoof
1403HL | Hilversum
1521NE | Westknollendam
1525RG | Wormerveer
1525RH | Wormerveer
1541LZ | Zaandijk

Deze lijken onjuist gegeven dat de Postcode 1222AB bijv. in Hilversum is. Het adres wat bijvoorbeeld bij 1222AB staat is als volgt:

Nieuwe Crailoseweg | 8 | GB4 | 1222AB | Bussum | Gooise Meren

De Nieuwe Crailoseweg is in Hilversum. 

https://www.postcode.nl/1222AB
https://www.google.com/maps/place/Nieuwe+Crailoseweg+8,+1222+AB+Hilversum/

Klopt deze aanname?

**Comment by justb4** [comment]
Het kan m.i. voorkomen dat een Postcode (althans volgens de Kadaster BAG) in 2 woonplaatsen ligt, althans als ik op 1222AB via Kadaster PDOK WFS zoek in adressen-laag (dus niet NLExtract) krijg ik volgend resultaat (alle adressen met PC 1222AB):

![image](https://user-images.githubusercontent.com/582630/53745168-c7d6aa80-3e9e-11e9-98e8-32e53b3e10c2.png)

Nieuwe Crailoseweg  8 zelf bestaat niet. Wel varianten met verschillende huisletters en/of huisnummertoevoegingen. Van laatste: GB4 ligt in woonplaats Bussum (gem. Gooische Meren), overigen in Hilversum.

**Comment by fsteggink** [comment]
Huisnr 8 is wel in de BAG viewer te vinden: https://bagviewer.kadaster.nl/lvbag/bag-viewer/index.html#?searchQuery=1222%20ab%208&resultOffset=0&objectId=0402200001611208&geometry.x=140198.649&geometry.y=473405.022&zoomlevel=6&detailsObjectId=0381010000028721

**Comment by justb4** [comment]
Ja maar dat is m.i. dezelfde `nummeraanduiding` (id `0381200000105407` ) als de eerste in mijn lijstje boven: deze heeft **GB4** als `huisnummertoevoeging`.

**Comment by borrob** [comment]
Via de bag-viewer is nr 8 (zonder toevoegingen) wel te vinden en ligt het in Hilversum (zie screenshot). Alleen met de 'GB4' toevoeging ligt het in Bussum (gemeente Gooise Meren). Misschien heeft het wel de postcode van Hilversum gekregen, omdat het niet meer dan een bijgebouw is van het RailPro opslagterrein?

Voor 1403HL liggen een aantal adressen in Hilversum. Één van de adressen is een manege en op hun contactpagina vertellen ze dat het Bussum is ([link](https://www.sportclubgooieneemland.nl/paardrijden/contact/)).

Voor oorsprong wordt de postcode toch niet door het kadaster opgezet, maar eigenlijk door PostNL ? Worden adressen onder een nieuwe postcode ingedeeld als de gemeentegrenzen verschuiven?

<img width="789" alt="schermafbeelding 2019-03-06 om 21 41 44" src="https://user-images.githubusercontent.com/5207393/53912303-f9937100-4058-11e9-8930-fb5722a7d284.png">

**Comment by justb4** [comment]
Inderdaad @borrob ! Ik had te snel gekeken. Nummeraanduiding `0402200001611208` is idd nummer 8 zonder toevoegingen. De BAGViewer zal direct op de BAG kijken terwijl de PDOK `inspireadressen` WFS (zie mijn plaatje boven) alsook NLExtract `adres` tabel afgeleid zijn daarvan middels vaak complexe JOINs en bij PDOK mogelijk met FME (eerste versies `inspireadressen` 
 2011-2013 waren wel met NLExtract door ondergetekende bij PDOK overigens). To be continued.

**Comment by justb4** [comment]
@marcojanssen je noemt *In de tabel adres...* : we hebben meer versie gegevens nodig:

* waar komt die adres tabel vandaan? Download van data.nlextract.nl of zelf met NLExtract aangemaakt? Anders?
* evt software versies
* bij download de datum van de BAG

Als ik bijv in de `adres(_full)` tabel van laatste BAG (8 feb 2019) zoals door NLExtract verwerkt in PostGIS, zie ik het voorbeeld (1222AB huisnummer 8, nummeraanduiding `0402200001611208`) *wel* met juiste woonplaats/gemeentenaam en zonder huisnummer toevoegingen:

![image](https://user-images.githubusercontent.com/582630/53953431-94c92c80-40d3-11e9-8552-4fec7ab232e9.png)

**Comment by marcojanssen** [comment]
@justb4 
De data komt van een download van NLextract (https://data.nlextract.nl/bag/postgis/bag-laatst.backup)
Heb continu de laatste versie gebruikt (januari, februari en nu maart)

Versies van de huidige versie zijn als volgt:

```
schema_versie,1.4.0
software_versie,1.1.4
schema_creatie,11-Mar-2019 23:02:27
gem_woonplaats_rel_datum,20190308
levering_xml,"<v20:BAG-Extract-Levering xmlns:v20=""http://www.kadaster.nl/schemas/bag-verstrekkingen/extract-levering/v20090901"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:v201=""http://www.kadaster.nl/schemas/bag-verstrekkingen/extract-meta/v20090901"" xmlns:v202=""http://www.kadaster.nl/schemas/bag-verstrekkingen/extract-selecties/v20090901"" xsi:schemaLocation=""http://www.kadaster.nl/schemas/bag-verstrekkingen/extract-levering/v20090901 http://www.kadaster.nl/schemas/bag-verstrekkingen/extract-levering/v20090901/BagvsExtractLeveringsdocument-1.3.xsd"">
    <v20:metadata>
        <v201:Klantgegevens>
            <v201:Klantnummer>814891</v201:Klantnummer>
            <v201:Klantnaam>Kadaster PDOK</v201:Klantnaam>
        </v201:Klantgegevens>
        <v201:Ordergegevens>
            <v201:Ordernummer>5013469</v201:Ordernummer>
            <v201:Leveringnummer>1000067571</v201:Leveringnummer>
        </v201:Ordergegevens>
        <v201:Bestelgegevens>
            <v201:Besteldatum>2014-02-13</v201:Besteldatum>
            <v201:Label>96000631</v201:Label>
        </v201:Bestelgegevens>
        <v201:Productgegevens>
            <v201:Productcode>DNLDLXAE02</v201:Productcode>
            <v201:Kanaal>DOWNLOAD</v201:Kanaal>
            <v201:GebiedType>NLD</v201:GebiedType>
            <v201:Gegevensvariant>LEVENSCYCLUS</v201:Gegevensvariant>
            <v201:Formaat>XML</v201:Formaat>
            <v201:Producttype>EXTRACT</v201:Producttype>
            <v201:Productversie>02</v201:Productversie>
        </v201:Productgegevens>
        <v201:BestandInfo>
            <v201:Bestandsnaam>DNLDLXAE02-814891-5013469-08032019.zip</v201:Bestandsnaam>
            <v201:Draaimoment>2019-03-08T17:29:20.422+01:00</v201:Draaimoment>
        </v201:BestandInfo>
    </v20:metadata>
    <v20:antwoord>
        <v20:vraag>
            <v202:LVC-Extract>
                <v202:gegVarLevenscyclus>true</v202:gegVarLevenscyclus>
                <v202:productcode>DNLDLXAE02</v202:productcode>
                <v202:StandTechnischeDatum>20190308</v202:StandTechnischeDatum>
            </v202:LVC-Extract>
            <v202:Leverfrequentie>
                <v202:periode>
                    <v202:maand>true</v202:maand>
                </v202:periode>
            </v202:Leverfrequentie>
            <v202:Gebied-Registratief>
                <v202:Gebied-NLD>
                    <v202:GebiedIdentificatie>4296</v202:GebiedIdentificatie>
                    <v202:GebiedNaam>NLD-0096000631</v202:GebiedNaam>
                    <v202:gebiedTypeNederland>true</v202:gebiedTypeNederland>
                </v202:Gebied-NLD>
            </v202:Gebied-Registratief>
            <v202:SchemaInfo>
                <v202:Schemanaam>BagvsExtractDeelbestandExtractLvc-1.4.xsd</v202:Schemanaam>
                <v202:Schemaversie>20090901</v202:Schemaversie>
                <v202:XML>true</v202:XML>
            </v202:SchemaInfo>
        </v20:vraag>
        <v20:producten/>
    </v20:antwoord>
</v20:BAG-Extract-Levering>
"
extract_datum, 20190308
```

Voor nummeraanduiding `0402200001611208` zie ik ook geen toevoeging, mijn vraag was echter waar het adres met nummeraanduiding `0381200000105407` vandaan komt. Deze lijkt onjuist ivm de overige adressen

![image](https://user-images.githubusercontent.com/2293642/55077107-3f12ef00-5097-11e9-9c17-ae78ff2cb5cc.png)

**Comment by marcojanssen** [comment]
En zo zijn er meerdere gevallen waar steeds een enkel adres gekoppeld is die geheel aan een andere stad toegekend is.

![image](https://user-images.githubusercontent.com/2293642/55077264-93b66a00-5097-11e9-9cc6-0be0db8cb945.png)

![image](https://user-images.githubusercontent.com/2293642/55077329-c1031800-5097-11e9-897c-f6fe5a9cce5b.png)

![image](https://user-images.githubusercontent.com/2293642/55077370-d9733280-5097-11e9-8b8c-a902569e2955.png)

**Comment by justb4** [comment]
We zijn via issue #302 de adres tabellen geheel opnieuw aan het afleiden. Dan opnieuw checken. Nu sluiten evt heropenen.
