### ISSUE TITLE
BGT geometrie_multivlak ontbreekt bij pand

### ISSUE THREAD

**Issue by bspiering** [nlextract/NLExtract#264]
Het attribuut geometrie_multivlak ontbreekt in de tabel pand

**Comment by fsteggink** [comment]
De multivlakgeometrie van een pand zit in de kolom geometrie_vlak. Dit is een MultiSurface geometrie:
```
bgt=> \d pand
                               Table "latest.pand"
                Column                |             Type             | Modifiers
--------------------------------------+------------------------------+-----------
 ogc_fid                              | integer                      | not null
 geometrie_vlak                       | geometry(MultiSurface,28992) |
 geometrie_nummeraanduiding           | geometry(Point,28992)        |
 gml_id                               | character varying            | not null
 namespace                            | character varying(8)         |
 lokaalid                             | character varying(38)        |
 objectbegintijd                      | date                         |
 objecteindtijd                       | date                         |
 tijdstipregistratie                  | timestamp with time zone     |
 eindregistratie                      | timestamp with time zone     |
 lv_publicatiedatum                   | timestamp with time zone     |
 bronhouder                           | character varying(5)         |
 inonderzoek                          | boolean                      |
 relatievehoogteligging               | integer                      |
 bgt_status                           | character varying(255)       |
 plus_status                          | character varying(255)       |
 identificatiebagpnd                  | character varying(16)        |
 nummeraanduidingtekst                | character varying(255)       |
 nummeraanduidinghoek                 | double precision             |
 identificatiebagvbolaagstehuisnummer | character varying(16)        |
 identificatiebagvbohoogstehuisnummer | character varying(16)        |
Indexes:
    "pand_pkey" PRIMARY KEY, btree (ogc_fid)
    "pand_bgt_status_idx" btree (bgt_status)
    "pand_eindregistratie_idx" btree (eindregistratie)
    "pand_geometrie_nummeraanduiding_geom_idx" gist (geometrie_nummeraanduiding)
    "pand_geometrie_vlak_geom_idx" gist (geometrie_vlak)
    "pand_plus_status_idx" btree (plus_status)
```

Hier heb ik de string "multi" weggehaald, omdat dat hier nauwelijks waarde toevoegt.

Dit zijn de aantallen geometry parts:
```
bgt=> select num, count(*) from (select st_numgeometries(geometrie_vlak) num from pandactueelbestaand) a group by num order by num;
 num |  count
-----+---------
   1 | 9989128
   2 |   16298
   3 |    3735
   4 |    1603
   5 |    1182
   6 |     639
   7 |     489
   8 |     377
   9 |     328
  10 |     244
  11 |     224
  12 |     207
  13 |     173
  14 |     125
  15 |     120
  16 |      71
  17 |      93
  18 |      57
  19 |      72
  20 |      43
  21 |      45
  22 |      42
  23 |      50
  24 |      31
  25 |      37
  26 |      25
  27 |      25
  28 |      20
  29 |      50
  30 |      20
  31 |      49
  32 |      17
  33 |      14
  34 |       9
  35 |      12
  36 |      17
  37 |       5
  38 |       8
  39 |       7
  40 |       5
  41 |       6
  42 |       8
  43 |       4
  44 |       6
  45 |       7
  46 |       3
  47 |       2
  48 |       4
  49 |       5
  50 |       5
  51 |       4
  52 |       4
  53 |       2
  54 |       1
  55 |       3
  56 |       5
  57 |       2
  58 |       1
  59 |       1
  60 |       2
  61 |       1
  62 |       3
  64 |       1
  65 |       2
  66 |       1
  67 |       2
  68 |       1
  69 |       2
  70 |       1
  72 |       1
  73 |       2
  74 |       1
  76 |       1
  78 |       2
  80 |       1
  81 |       1
  83 |       2
  85 |       1
  89 |       1
  92 |       1
  96 |       1
  97 |       2
  99 |       1
 100 |       2
 104 |       1
 113 |       2
 115 |       1
 119 |       1
 122 |       1
 123 |       1
 138 |       1
 193 |       1
 221 |       1
 222 |       1
 244 |       1
(95 rows)
```

**Comment by bspiering** [comment]
Helder, dank voor je snelle reactie!
Met vriendelijke groet,



Boudewijn Spiering

Adviseur
T +31 88 811 40 70
M +31 6 53 74 05 41
boudewijn.spiering@sweco.nl

Sweco Nederland B.V.
K.P. van der Mandelelaan 41-43
3062 MB Rotterdam
T +31 88 811 66 00
Handelsregister 30129769
www.sweco.nl<https://www.sweco.nl/?utm_source=signature-sweco&utm_medium=email>

[cid:image001.jpg@01D4D7E8.6D31C5F0]





Volg ons op LinkedIn.<https://goo.gl/Whw4U1> Hier delen wij onze kennis, vertellen je wat ons drijft en waar we in geloven.

Van: Frank Steggink <notifications@github.com>
Verzonden: maandag 11 maart 2019 08:49
Aan: nlextract/NLExtract <NLExtract@noreply.github.com>
CC: Spiering, Boudewijn <Boudewijn.Spiering@sweco.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [nlextract/NLExtract] BGT geometrie_multivlak ontbreekt bij pand (#264)


De multivlakgeometrie van een pand zit in de kolom geometrie_vlak. Dit is een MultiSurface geometrie:

bgt=> \d pand

                               Table "latest.pand"

                Column                |             Type             | Modifiers

--------------------------------------+------------------------------+-----------

 ogc_fid                              | integer                      | not null

 geometrie_vlak                       | geometry(MultiSurface,28992) |

 geometrie_nummeraanduiding           | geometry(Point,28992)        |

 gml_id                               | character varying            | not null

 namespace                            | character varying(8)         |

 lokaalid                             | character varying(38)        |

 objectbegintijd                      | date                         |

 objecteindtijd                       | date                         |

 tijdstipregistratie                  | timestamp with time zone     |

 eindregistratie                      | timestamp with time zone     |

 lv_publicatiedatum                   | timestamp with time zone     |

 bronhouder                           | character varying(5)         |

 inonderzoek                          | boolean                      |

 relatievehoogteligging               | integer                      |

 bgt_status                           | character varying(255)       |

 plus_status                          | character varying(255)       |

 identificatiebagpnd                  | character varying(16)        |

 nummeraanduidingtekst                | character varying(255)       |

 nummeraanduidinghoek                 | double precision             |

 identificatiebagvbolaagstehuisnummer | character varying(16)        |

 identificatiebagvbohoogstehuisnummer | character varying(16)        |

Indexes:

    "pand_pkey" PRIMARY KEY, btree (ogc_fid)

    "pand_bgt_status_idx" btree (bgt_status)

    "pand_eindregistratie_idx" btree (eindregistratie)

    "pand_geometrie_nummeraanduiding_geom_idx" gist (geometrie_nummeraanduiding)

    "pand_geometrie_vlak_geom_idx" gist (geometrie_vlak)

    "pand_plus_status_idx" btree (plus_status)

Hier heb ik de string "multi" weggehaald, omdat dat hier nauwelijks waarde toevoegt.

Dit zijn de aantallen geometry parts:

bgt=> select num, count(*) from (select st_numgeometries(geometrie_vlak) num from pandactueelbestaand) a group by num order by num;

 num |  count

-----+---------

   1 | 9989128

   2 |   16298

   3 |    3735

   4 |    1603

   5 |    1182

   6 |     639

   7 |     489

   8 |     377

   9 |     328

  10 |     244

  11 |     224

  12 |     207

  13 |     173

  14 |     125

  15 |     120

  16 |      71

  17 |      93

  18 |      57

  19 |      72

  20 |      43

  21 |      45

  22 |      42

  23 |      50

  24 |      31

  25 |      37

  26 |      25

  27 |      25

  28 |      20

  29 |      50

  30 |      20

  31 |      49

  32 |      17

  33 |      14

  34 |       9

  35 |      12

  36 |      17

  37 |       5

  38 |       8

  39 |       7

  40 |       5

  41 |       6

  42 |       8

  43 |       4

  44 |       6

  45 |       7

  46 |       3

  47 |       2

  48 |       4

  49 |       5

  50 |       5

  51 |       4

  52 |       4

  53 |       2

  54 |       1

  55 |       3

  56 |       5

  57 |       2

  58 |       1

  59 |       1

  60 |       2

  61 |       1

  62 |       3

  64 |       1

  65 |       2

  66 |       1

  67 |       2

  68 |       1

  69 |       2

  70 |       1

  72 |       1

  73 |       2

  74 |       1

  76 |       1

  78 |       2

  80 |       1

  81 |       1

  83 |       2

  85 |       1

  89 |       1

  92 |       1

  96 |       1

  97 |       2

  99 |       1

 100 |       2

 104 |       1

 113 |       2

 115 |       1

 119 |       1

 122 |       1

 123 |       1

 138 |       1

 193 |       1

 221 |       1

 222 |       1

 244 |       1

(95 rows)
