### ISSUE TITLE
BGT Geo punt in een een Multivlak identificeren

### ISSUE THREAD

**Issue by Nielsien** [nlextract/NLExtract#266]
Hallo,

Ik probeer een geopunt te identificeren in een multivlak, hiervoor wil ik bijvoorbeeld alle panden in Almere kunnen identificeren.
Ik ben dit probleem aangegaan door ST_Within en ST_Contains te gebruiken, bij beide heb ik weinig succes gekregen. Hij geeft namelijk altijd false of null terug. 
Hieronder heb ik een voorbeeld van de query's die ik gebruikt heb:

`select * from buurt where ST_WITHIN(geometrie_vlak, ST_GeomFromText('POINT(52.36708060543268 5.239647416553453)', 4326)) = true` 

`select ST_WITHIN(geometrie_vlak, ST_GeomFromText('POINT(52.36708060543268 5.239647416553453)', 4326)) from wijk`

Hier gebruik ik een long en lat die ergens op een huis in Almere staat, ik gebruik hier een hardcoded geopunt om te testen of het werkt. Mijn uiteindelijke doel is om alle panden uit een stad of dorp in een query te kunnen vinden door middel van deze geopunten.
Ik heb dit met meerdere databases geprobeerd maar lukte het ook niet met die databases.

Groetjes, Niels

**Comment by fsteggink** [comment]
Beste Niels, de issuelijst van NLExtract is voor het rapporteren van issues m.b.t. NLExtract. Vragen over het gebruik van de data kun je beter op de [OSGeo.NL mailinglijst](https://lists.osgeo.org/mailman/listinfo/dutch) of op het [Geoforum](https://geoforum.nl/) zetten.

Er zijn meerdere redenen waarom je geen resultaat krijgt:
* Je moet de lat en lon omdraaien. Anders krijg je een punt voor de kust van Somalië: 
```
bgt=> select st_astext(st_transform(ST_GeomFromText('POINT(52.36708060543268 5.239647416553453)', 4326), 28992));
                 st_astext
-------------------------------------------
 POINT(6387071.19829431 -3626843.03677566)
(1 row)


bgt=> select st_astext(st_transform(ST_GeomFromText('POINT(5.239647416553453 52.36708060543268)', 4326), 28992));
                st_astext
------------------------------------------
 POINT(144950.050031605 486587.656365091)
(1 row)
```
Het eerste resultaat ligt ver buiten Nederland en het 2e resultaat ligt wel in Nederland.

* Je moet ook de argumenten van [ST_Within](https://postgis.net/docs/ST_Within.html) omdraaien. Het eerste argument moet het punt zijn en het tweede argument het vlak. Als je [ST_Contains](https://postgis.net/docs/ST_Contains.html) zou gebruiken, zou de volgorde wel goed zijn.
* Verder bevatten de tabellen wij en buurt slechts heel weinig data. Maar weinig bronhouders hebben deze data gevuld. Volgens mij minder dan 10 gemeenten. Almere zit hier niet bij.
* Als je de tabel buurt of wijk bevraagt, kun je mogelijk historische gegevens terugkrijgen. Dit is waarschijnlijk ongewenst. Je kunt hiervoor beter de views buurtactueelbestaand resp. wijkactueelbestaand gebruiken.
* I.v.m. performance zou ik de coördinaat van de query eerst transformeren naar RD, dus via st_transform(..., 28992) zoals in mijn voorbeeld hierboven. Ik heb niet gecheckt met de query planner of dit daadwerkelijk verschil uitmaakt en gezien de hoeveelheid data zal het weinig uitmaken, maar in andere gevallen zou het veel verschil kunnen uitmaken.

Met vriendelijke groet,
Frank Steggink
