### ISSUE TITLE
BRK download linkjes kloppen niet

### ISSUE THREAD

**Issue by stvno** [nlextract/NLExtract#267]
Op https://nlextract.nl/downloads/ staan niet werkende URLs voor de BRK downloads:

* `https://data.nlextract.nl/brk/postgis/brk-latest.backup`
* `https://data.nlextract.nl/brk/postgis/brk-kadgrens-latest.backup`

Echter de bestanden heten:

* `https://data.nlextract.nl/brk/postgis/brk-201903.dmp`
* `https://data.nlextract.nl/brk/postgis/brk-kadgrens_201903.dmp`

Is het mogelijk om een symlink te maken die volgens het `-latest.backup` principe werkt? Dan werken de linkjes op de download pagina weer en is het makkelijker automatisch te checken of er een nieuwe versie staat

**Comment by justb4** [comment]
Ok, done, linken zat nog niet in cron-script, of was weggevallen. Nu wel. @fsteggink : heb `brk-load.sh` dus aangepast om op einde te symlinken net als bij BAG. Weblinks zouden nu goed moeten zijn, alhoewel er wat inconsistentie is in naamgeving tussen de basisregistraties (`.dmp` vs `.backup`, `laatst` vs `latest`) maar is historisch gegroeid zo....Sluiten indien ok. Straks checken of BRK-april automatisch goed gaat.

**Comment by fsteggink** [comment]
Issue werkt. Oorzaak van dat het niet werkte is dat ik alle dumps vorig jaar op de NLExtract hacking day de extensie 'backup' had gegeven ipv 'dmp'. Niet doorgevoerd voor de DKK op de NLExtract server, omdat jij (@justb4) die beheert.
