### ISSUE TITLE
BGT: Er is nu slechts maximaal 1 nummeraanduidingreeks per pand

### ISSUE THREAD

**Issue by bspiering** [nlextract/NLExtract#268]

**Comment by bspiering** [comment]
Per pand is er nu maximaal maar 1 nummeraanduidingreeks opgenomen, maar in de BGT komen meerdere reeksen voor als de verblijfsobjecten van 1 pand aan meerdere openbare ruimten liggen. Bovendien blijkt bijvoorbeeld bij pand met identificatiebagpnd ='0451100000009893' dat de geometrie van de nummeraanduidingreeks niet klopt met overige gegevens van de nummeraanduidingreeks (de geometrie is van huisnummer '2A' en nummeraanduidingtekst='91-99'). Voorstel: toch weer een aparte tabel nummeraanduidingreeks maken (zie issue #225),  waarbij de nummeraanduidingreeksen via lokaalid en/of via identificatiebagpnd zijn te relateren aan het juiste pand.

**Comment by fsteggink** [comment]
Tevens gemeld door Rob Egelmeer van Geonovation op de mailinglijst

**Comment by fsteggink** [comment]
Ik heb weer een aparte tabel voor nummeraanduidingen gemaakt. Ze worden van de pand-features op een vergelijkbare manier als de openbareruimtelabels afgesplitst. De OrlHandler heb ik hiervoor gerefactored tot een SubFeatureHandler (via een tijdelijke 2e handler genaamd PandHandler). Zie commit historie.

De tabelstructuur van Pand is als volgt:
```
bgt=> \d pand
                        Table "latest.pand"
         Column         |             Type             | Modifiers
------------------------+------------------------------+-----------
 ogc_fid                | integer                      | not null
 geometrie_vlak         | geometry(MultiSurface,28992) |
 gml_id                 | character varying            | not null
 namespace              | character varying(8)         |
 lokaalid               | character varying(38)        |
 objectbegintijd        | date                         |
 objecteindtijd         | date                         |
 tijdstipregistratie    | timestamp with time zone     |
 eindregistratie        | timestamp with time zone     |
 lv_publicatiedatum     | timestamp with time zone     |
 bronhouder             | character varying(5)         |
 inonderzoek            | boolean                      |
 relatievehoogteligging | integer                      |
 bgt_status             | character varying(255)       |
 plus_status            | character varying(255)       |
 identificatiebagpnd    | character varying(16)        |
Indexes:
    "pand_pkey" PRIMARY KEY, btree (ogc_fid)
    "pand_bgt_status_idx" btree (bgt_status)
    "pand_eindregistratie_idx" btree (eindregistratie)
    "pand_geometrie_vlak_geom_idx" gist (geometrie_vlak)
    "pand_plus_status_idx" btree (plus_status)
```

De structuur van de nieuwe tabel Pand_nummeraanduiding is als volgt:
```
bgt=> \d pand_nummeraanduiding
                    Table "latest.pand_nummeraanduiding"
                Column                |           Type           | Modifiers
--------------------------------------+--------------------------+-----------
 ogc_fid                              | integer                  | not null
 geometrie_nummeraanduiding           | geometry(Point,28992)    |
 gml_id                               | character varying        | not null
 namespace                            | character varying(8)     |
 lokaalid                             | character varying(38)    |
 objectbegintijd                      | date                     |
 objecteindtijd                       | date                     |
 tijdstipregistratie                  | timestamp with time zone |
 eindregistratie                      | timestamp with time zone |
 lv_publicatiedatum                   | timestamp with time zone |
 bronhouder                           | character varying(5)     |
 inonderzoek                          | boolean                  |
 relatievehoogteligging               | integer                  |
 bgt_status                           | character varying(255)   |
 plus_status                          | character varying(255)   |
 identificatiebagpnd                  | character varying(16)    |
 nummeraanduidingtekst                | character varying(255)   |
 nummeraanduidinghoek                 | double precision         |
 identificatiebagvbolaagstehuisnummer | character varying(16)    |
 identificatiebagvbohoogstehuisnummer | character varying(16)    |
Indexes:
    "pand_nummeraanduiding_pkey" PRIMARY KEY, btree (ogc_fid)
    "pand_geometrie_nummeraanduiding_geom_idx" gist (geometrie_nummeraanduiding)
    "pand_nummeraanduiding_bgt_status_idx" btree (bgt_status)
    "pand_nummeraanduiding_eindregistratie_idx" btree (eindregistratie)
    "pand_nummeraanduiding_plus_status_idx" btree (plus_status)
```

Ik heb ervoor gekozen om alle 'common' pand-kolommen te kopiëren, zodat alle relevante informatie beschikbaar is. Er is dan ook een view pand_nummeraanduidingactueelbestaand gemaakt.

Gebruikers van de NLExtract dump hoeven dan waarschijnlijk geen maatregelen te treffen in hun toepassingen, maar alleen de tabel te hernoemen als ze nummeraanduidingen gebruiken. Alleen wanneer men iets doet met zowel de pandgeometrie als met de nummeraanduiding-geometrie of andere attributen, moet er wel wat meer aangepast worden. Dit is applicatie-afhankelijk en m.i. onvermijdelijk.

I.v.m. verhelpen redundantie zouden de kolommen "nummeraanduidingtekst" en "nummeraanduidinghoek" weer kunnen worden hernoemd naar respectievelijk "tekst" en "hoek", maar daar hebben bestaande applicaties meer last van.

**Comment by fsteggink** [comment]
Zie commit 05ec8a2c27deee78041598554bd60118ca3d85e5 voor de refactoring naar SubFeatureHandler.
