### ISSUE TITLE
Is pandgebruiksdoelen.sql nog actueel?

### ISSUE THREAD

**Issue by jhpoosthoek** [nlextract/NLExtract#269]
Ik zag dit SQL script: https://github.com/nlextract/NLExtract/blob/master/bag/db/script/pandgebruiksdoelen.sql

Ik heb het iets aangepast: https://gist.github.com/jhpoosthoek/fd8a6ca75229a319758b39ad96cc9008

Maar omdat het uit 2014 komt vroeg ik mij af of dit script nog actueel is?

**Comment by justb4** [comment]
Het betreft een gedoneerd script. Wordt verder niet in bijv productie van NLExtract BAG dumps gebruikt. Op zich zijn meerdere scripts uit die tijd. Omdat de BAG structuur niet is veranderd en in tabellen hoogstens type `identificatie` (Text ipv Int) denk ik dat script nog geldig is. Maar zou test moeten uitwijzen.
