### ISSUE TITLE
Buurt en wijk toevoegen aan CSV-bestand

### ISSUE THREAD

**Issue by FrieseWoudloper** [nlextract/NLExtract#271]
Zouden het unieke id en de naam van de buurt en wijk toegevoegd kunnen worden aan het (uitgebreide) CSV-bestand? Dat zou heel handig zijn voor analyses.

**Comment by justb4** [comment]
is idd gewenst door velen, goed weer op te rakelen,  zie issue #64 , evt suggesties, bijv welke bron, modellering mbt gem./wpl, graag bij dat issue en deze sluiten (duplicate).
