### ISSUE TITLE
BRK Kadastrale Kaart (DKK) ETL: upgrade voor BRK-DKK v4

### ISSUE THREAD

**Issue by justb4** [nlextract/NLExtract#272]
## Achtergrond
In kort: Kadaster/PDOK brengt nieuwe versie (v4) van Digitale Kadastrale Kaart uit. NLExtract BRK-DKK ETL is gebaseerd op v3. Zie ook: https://geoforum.nl/t/nu-dagelijkse-actualiteit-in-nieuwe-kadastrale-kaart/3305
Citaat: *Wat betreft de data kent de KadastraleKaartV4 andere feature types dan de KadastraleKaartV3. Waar de KadastraleKaartV3 de feature types Grenzen, Percelen, Annotaties en Bebouwing had, daar heeft de KadastraleKaartV4 de feature types KadastraleGrens, Perceel, NummeraanduidingReeks, OpenbareruimteNaam en Bebouwing. De eerste twee feature types – te weten KadastraleGrens en Perceel – zijn gelijk aan de feature types Grenzen en Percelen van de KadastraleKaartV3. Annotaties is opgedeeld in NummeraanduidingReeks en OpenbareruimteNaam. Tot slot is Bebouwing gelijk gebleven. Het document “Verschillen Kadastrale kaart V3 en V4” op https://kadaster.nl/schemas2 beschrijft deze verschillen in detail.
De update frequentie van de verschillende feature types is ook gewijzigd. De KadastraleGrens en Perceel worden dagelijks geüpdatet ten opzichte van maandelijks bij de KadastraleKaartV3. De NummeraanduidingReeks, OpenbareruimteNaam en Bebouwing zijn een selectie uit de BGT en worden eens per maand geüpdatet."* 
Opm: volgens mij is `Bebouwing` niet hetzelfde maar vervangen door BGT Pand.
Download bijv een klein stukje via de viewer: https://downloads.pdok.nl/kadastralekaart/viewer/.

## Probleem
Volgens mijn gegevens is er ook sinds 30 sept 2019 geen maandelijkse download van de BRK-DKK v3 meer. [NLExtract BRK-DKK ETL](https://github.com/nlextract/NLExtract/tree/master/brk/etl) moet dus herzien worden om v4 te ondersteunen. 

## Analyse

* Voor `DKK Perceel` en `DKK Kadastralegrens` vallen de wijzigingen op zich mee. Zou in principe alleen een GFS file wijziging zijn. Echter er is ook meer historie en status velden bijgekomen ala BAG zoals `<h:beginGeldigheid>2001-03-19T14:25:31.000</h:beginGeldigheid>`. Vraag is of er filtering gedaan moet worden om "actueelbestaande" percelen in bijv VIEWs uit te filteren.

* Bebouwing komt uit BGT (CityGML), vraag is of we dit uberhaupt nog gaan meenemen
* Idem voor Annotaties (worden `NummeraanduidingReeks, OpenbareruimteNaam` )

**Comment by fsteggink** [comment]
Peter Barto van het Kadaster heeft vanochtend op het Geoforum aangegeven dat de V3-downloads ook nog de rest van dit jaar beschikbaar blijven: https://geoforum.nl/t/nu-dagelijkse-actualiteit-in-nieuwe-kadastrale-kaart/3305/7

V.w.b. bebouwing en annotatie: ik zou dit wel in het DKK-proces meenemen. Ook al is het een kopie van de BGT, het wordt wel met de DKK meegeleverd. dus vind ik het ook zinvol om dit in de downloads beschikbaar te stellen. Wel zouden we de downloads kunnen opsplitsen in 4 bestanden; 1 dump per feature. Kadstrale grens is nu al gescheiden van perceel en de rest. Mogelijk hiernaast toch ook een dump met de volledige dataset beschikbaar stellen, want ook daar zijn vast afnemers voor te vinden. We kunnen de definities van deze features uit het GFS-bestand van de BGT halen.

Wat de nieuwe velden betreft: ik heb begrepen dat alleen actuele data wordt geleverd. Extra filtering lijkt mij op dit moment nog niet nodig, maar het is beter om dit in de data te checken. En misschien is het verstandig om future proof te zijn.

**Comment by justb4** [comment]
@fsteggink m.i. `SubFeatureHandler` nodig voor `dkk_openbareruimtelabel` en `dkk_pand` GML bestanden.

**Comment by justb4** [comment]
@fsteggink moest `SubFeatureHandler` nog aardig aanpassen om andere niet-CityGML gebaseerde bestanden (bijv `Percelen.gml`) transparant door te `Stetl Filter`-en...

Omdat sommige afnemers nog steeds aan Python2 gebonden zijn, voorlopig in 1.4.1 branch, later mergen naar 1.5.0.

**Comment by justb4** [comment]
Zit in v1.4.1. (Python 2) maar moet nog gemerged naar master (Python3 ) en dan v1.5.0.

**Comment by justb4** [comment]
Zit in 1.5.0, handmatig, teveel issues anders.
