### ISSUE TITLE
bgt import of FunctioneelGebied fails in ogr2ogr due to an error in imgeo-v2.1.1.gfs

### ISSUE THREAD

**Issue by jajdnl** [nlextract/NLExtract#277]
The .gfs file created from the part below causes ogr2ogr to crash with :
      terminate called after throwing an instance of 'std::logic_error'
      what():  basic_string::_M_construct null not valid
     Aborted (core dumped)
(running on ubuntu Ubuntu 18.04.4 LTS 
 ogr2ogr --version: GDAL 3.0.2, released 2019/10/28)

When  
`     <Name>naam</Name><Name>naam</Name> `
Is changed to 
`      <Name>naam</Name><ElementPath>naam</ElementPath>`
It works again 

`   
    <PropertyDefn>
      <Name>bgt_type</Name>
      <ElementPath>bgt-type</ElementPath>
      <Type>String</Type>
      <Width>255</Width>
    </PropertyDefn>
    <PropertyDefn>
      <Name>plus_type</Name>
      <ElementPath>plus-type</ElementPath>
      <Type>String</Type>
      <Width>255</Width>
    </PropertyDefn>
    <PropertyDefn>
      <Name>naam</Name>
      <Name>naam</Name>
      <Type>String</Type>
      <Width>255</Width>
    </PropertyDefn>
    `

**Comment by fsteggink** [comment]
Thank you for reporting. As I haven't migrated to GDAL 3 yet, I haven't run into this issue. In my database the "naam" field is simply null everywhere, although this field should indeed contain values.

As for the usefulness of this field, the quality seems to be severely lacking. In my test file, downloaded 2,5 months ago, these values are used in the naam column:
```
bgt=> select naam eindregistratie, objecteindtijd from functioneelgebied_tmp where naam is not null;
      eindregistratie      | objecteindtijd
---------------------------+----------------
 -                         |
 -                         |
 -                         |
 -                         |
 test GEO-BOR              | 2019-07-30
 test                      | 2018-02-14
 Waterstaatswerk           |
 Waterstaatswerk           |
 Waterstaatswerk           |
 -                         |
 -                         |
 -                         |
 Brandenburg               |
 Brandenburg               |
 Brandenburg               |
 Begraafplaats Noorderveld |
 Begraafplaats Noorderveld |
 TEST OBJECT               | 2018-02-13
 test                      | 2018-02-14
 Begraafplaats Westbroek   |
 TESTEN VABV               | 2018-03-28
 TEST OBJECT               | 2018-02-13
 test GEO-BOR              | 2019-07-30
 test                      | 2018-02-14
 TESTEN VABV               | 2018-03-28
 test                      | 2018-02-14
(26 rows)
```
The test values are all from objects which are not current anymore.

As far as I can see, this typo is the only one in the GFS file. Please let us know if you encounter any other issues with GDAL 3.
