### ISSUE TITLE
cannot create class 'stetlbgt.subfeaturehandler.SubFeatureHandler'

### ISSUE THREAD

**Issue by jeroenVerdonschot** [nlextract/NLExtract#279]
Hoi,

ik krijg deze error. Dit komt omdat ik e.e.a. niet goed geïnstalleed heb maar ik niet wat. 

2020-03-22 12:52:15,852 factory ERROR cannot create class 'stetlbgt.subfeaturehandler.SubFeatureHandler'
2020-03-22 12:52:15,852 factory ERROR cannot create object instance from class 'stetlbgt.subfeaturehandler.SubFeatureHandler' e=No module named stetlbgt.subfeaturehandler

Dank je,

Jeroen

**Comment by justb4** [comment]
Kan aan je aanroep liggen: `stetlbgt.subfeaturehandler.SubFeatureHandler` moet in the `PYTHONPATH` zitten of anderzijds vindbaar.

**Comment by jeroenVerdonschot** [comment]
Top, dat was het. Ik heb niet zoveel python ervaring dus mijn excuses voor deze vraag.

**Comment by fsteggink** [comment]
Geeft niet. Integendeel: het gebruik van NLExtract moet geen "rocket science" zijn. Kun je uitleggen hoe je NLExtract aanroept? En welke versie gebruik je? Een release, of de git master?
Ik heb recent issue #278 ingeschoten om de documentatie te verbeteren. Dit betreft zowel de installatie alsmede de etl-xxx.sh/cmd scripts voor het aanroepen. Zie ook mijn recente opmerkingen bij #265.
