### ISSUE TITLE
BAG: ProgrammingError: function public.probe_geometry_columns() does not exist

### ISSUE THREAD

**Issue by kduvekot** [nlextract/NLExtract#284]
Tijdens het uitvoeren van de verschillende commando's om de BAG data te extraheren liep ik tegen de volgende fout op:

`-- Populeert public.geometry_columns
-- Dummy voor PostGIS 2+
SELECT public.probe_geometry_columns();
 met parameters None ['Traceback (most recent call last):\n', '  File "/home/ubuntu/nlextract-1.4.2/bag/src/postgresdb.py", line 108, in uitvoeren\n    self.cursor.execute(sql)\n', 'ProgrammingError: function public.probe_geometry_columns() does not exist\nLINE 46: SELECT public.probe_geometry_columns();\n                ^\nHINT:  No function matches the given name and argument types. You might need to add explicit type casts.\n\n']
`

Enig idee hoe dat op te lossen?
dit gaat dus fout tijdens ../db/script/gemeente-provincie-tabel.sql draaien

Dit is met release 1.4.2

**Comment by justb4** [comment]
Heb dit juist weggehaald in 1.4.2, omdat dit problemen gaf in PostGIS 2+. Was oude patch voor PostGIS 1, maar overbodig. Zie ook de file:
https://github.com/nlextract/NLExtract/blob/1.4.0/bag/db/script/bag-db.sql#L332 

maar zie nu dat ie vaker aangeroepen wordt, dus in https://github.com/nlextract/NLExtract/blob/1.4.0/bag/db/script/gemeente-provincie-tabel.sql#L46 , ja is dus bug! (Denk door mij niet opgemerkt omdat bij testen die functie in public schema stond...). Je kunt die laatste regel weghalen en kijken. (Neem aan dat je PostGIS 2+ gebruikt).

**Comment by justb4** [comment]
En op nog veel meer plekken aangeroepen:
https://github.com/nlextract/NLExtract/search?q=probe_geometry_columns&unscoped_q=probe_geometry_columns

**Comment by kduvekot** [comment]
Ik heb net handmatig de wijzigingen van [68eda53](https://github.com/nlextract/NLExtract/commit/68eda53729bff6489ba25620e829110a0fcc4478) doorgevoerd in mijn versie .. en dat zorgt er idd voor dat stap 3 (gemeente-provincie-tabel.sql) uitgevoed kan worden .. ik ga nu verder met stap 4 :-)
