### ISSUE TITLE
server closed the connection unexpectedly

### ISSUE THREAD

**Issue by tombouderij** [nlextract/NLExtract#286]
krijg deze error bij het uitvoeren van de adres-tabel.sql
Werkt wel bij een kleine bagextract (20MB), maar bij de volledige bagextract krijg ik telkens deze specifieke error bij dit script.

Software:
Postgres 9.5
Python2

**Comment by tombouderij** [comment]
extra info: deze error krijg ik als ik nlextract in een docker omgeving gebruik. Als ik de adres-tabel query in pgadmin uitvoert krijg ik niet deze error.

**Comment by fsteggink** [comment]
Ik kan dit issue in het algemeen reproduceren i.c.m. Docker en PostgreSQL. Ik heb gemerkt dat de verbinding wordt verbroken wanneer na minimaal 5 minuten er geen verkeer van de DB server naar de Docker-container is gegaan. Voor mijn eigen scripts kan ik hier omheen werken door de queries te optimaliseren. Vaak is er een goede performancewinst te behalen. Bij een groot script werkt het ook om het script statement voor statement uit te voeren. Maar bij bijv. de BGT-verwerking duurt het uitvoeren van het script create-final-tables-v2.1.1.sql bij mij meestal ongeveer een half uur, maar dit knalt er niet uit. Wellicht komt dat ook omdat dit uit losse statements bestaat.

V.w.b. het script adres-tabel.sql weet ik nog niet een suggestie. Zelf gebruik ik dit script niet.

**Comment by tombouderij** [comment]
Heb de adres-tabel query in meerdere bestanden gesplists. Dat werkte iets beter maar nog niet optimaal. Uiteindelijk opgelost door een Powershell script te gebruiken die de queries handmatig uitvoert door Postgres aan te roepen.
