### ISSUE TITLE
BGT downloads vernieuwing bij PDOK

### ISSUE THREAD

**Issue by justb4** [nlextract/NLExtract#287]
Uit de PDOK nieuwsbrief:

"Op 2 juni 2020 gaat de BGT over op een vernieuwde productieomgeving voor de downloads.  De overgangsperiode duurt tot 1 oktober van dit jaar: de huidige  download-omgeving en de beta (test) omgeving zullen dan ook vier maanden  naast de nieuwe download-omgeving blijven staan. Daarna worden de oude  leveringsmogelijkheden definitief gestopt.   Wat betekent dit voor u:   

* Er zijn nieuwe download-URL’s:     
* Voor de download-viewer: https://app.pdok.nl/lv/bgt/download-viewer/     
* Voor de API: https://api.pdok.nl/lv/bgt/download/v1_0/ui/   

De vernieuwing biedt u meer mogelijkheden:     
* API’ s zijn veranderd. Vaste kaartbladen zijn vervangen door het downloaden van interessegebieden;     
* Bij het downloaden van interessegebieden is selectie van gebied en features mogelijk;     
* Downloads draaien op andere infrastructuur;     
* Fouten en storingen m.b.t. trage downloads zijn verholpen;     
* Unieke URL’s worden per download gecreëerd.   

Vanaf 1 oktober 2020 is de oude downloadomgeving definitief niet meer bereikbaar.  PDOK verzoekt u dan ook om zo spoedig mogelijk over te schakelen naar de nieuwe, bovengenoemde download-URL’s."

**Comment by fsteggink** [comment]
Volgens mij hoeft hier niks voor te gebeuren in NLExtract. Dit betreft de links om de extracten te downloaden. Het datamodel is niet gewijzigd.

**Comment by justb4** [comment]
Ja klopt, kunnen we sluiten.
