### ISSUE TITLE
BGT download werkt niet meer

### ISSUE THREAD

**Issue by richardhinkamp** [nlextract/NLExtract#292]
De download van blocks via https://downloads.pdok.nl/service/extract.zip vanuit `bgt/etl/download-bgt.sh` werkt niet meer. Moet nu via https://api.pdok.nl/lv/bgt/download/v1_0/ui/ wat volgens #287 geen wijziging nodig zou hebben, maar toch wel?

**Comment by justb4** [comment]
Ja, oude downloads werken niet meer zie documentatie PDOK.
