### ISSUE TITLE
configparser not found

### ISSUE THREAD

**Issue by jasper-hve** [nlextract/NLExtract#295]
Mogelijk dat dit komt door mijn beperkte kennis van python, maar ik probeerde bagextract.py (uit versie 1.5.0.) uit te voeren (windows). Ik heb hiervoor de instructie gevolgd volgens: https://docs.nlextract.nl/en/latest/bagextract.html#instellingen 

Bij bagextract.py in cmd is dit de output:

![image](https://user-images.githubusercontent.com/75160646/100498159-90269080-3160-11eb-859d-af95786c9857.png)

Bedankt voor het beschikbaar maken van de scripts en evt antwoord op deze vraag.

**Comment by petersaalbrink** [comment]
Het ziet ernaar uit dat je python2 gebruikt (daar heet de stdlib ConfigParser ipv configparser), terwijl de huidige versie van de BAG-extract bedoeld is voor python3. Als je de mogelijkheid hebt om python3 te gebruiken, dan is dat aan te raden. Als je gebonden bent aan python2, zou je kunnen proberen terug te draaien naar een commit in deze repository van voor 12 februari 2020, maar het is niet gegarandeerd dat dat helpt.
Ik ga er overigens vanuit dat de documentatie achterloopt; die noemt inderdaad nog dat je python2 dient te gebruiken.

**Comment by justb4** [comment]
Ja NLExtract is nu volledig over op Python3 dus ConfigParser install niet nodig.
