### ISSUE TITLE
BAGv2 laden met GDAL < 3.2.2

### ISSUE THREAD

**Issue by sebastic** [nlextract/NLExtract#312]
De GDAL versie vereist voor de BAGLV driver is problematisch, deze versie zal de komende twee jaar niet breed beschikbaar zijn.

Het moet mogelijk zijn om ook met oudere GDAL de BAGv2 te laden.

Zie ook de [discussie op de mailinglist](https://groups.google.com/g/nlextract/c/8Jt_TfqAFW8/m/FHRp1FoPCAAJ)

**Comment by justb4** [comment]
Volgens mij is dit niet/nooit mogelijk: GDAL >= 3.4.0 is vereist, zie ook [Gitter Chat](https://gitter.im/nlextract/NLExtract?at=6212458c3ae95a1ec1630613), dus sluit ik voor nu.

**Comment by sebastic** [comment]
Ik heb een Python implementatie ontwikkeld om BAG 2.0 Extract data te verwerken met Stetl, die ondersteunt ook de Inactief, InOnderzoek, en NietBag data in tegenstelling tot de LVBAG driver in GDAL. Ook heeft het geen heel moderne GDAL nodig, alleen:
 * `ogr.CreateGeometryFromGML()`
 * `geom.Is3D()`
 * `geom.FlattenTo2D()`
 * `ogr.ForceToMultiPolygon()`
 * `geom.Centroid()`
 * `geom.ExportToWkb()`

Ondanks het gebruik van multiprocessing on meerdere zip files parallel te verwerken duurt het aanzienlijk langer om alle data te verwerken in verhouding tot de LVBAG driver (die lijkt XML files in parallel te verwerken), maar redelijk in lijn met de tijd die het duurde om BAGv1 data te verwerken.

Er is nooit feedback gekomen op de [BAGv2 changes](https://groups.google.com/g/nlextract/c/q0TtlpEYdMY), dus deze changes heb ik nooit geupstreamed.
