### ISSUE TITLE
BAGv2 error type "geometry" does not exist

### ISSUE THREAD

**Issue by sebastic** [nlextract/NLExtract#316]
`sql/create-tables.sql` faalt:
```
2021-04-23 18:09:34,160 fileinput INFO Read/parse for start for file=sql/create-tables.sql....
2021-04-23 18:09:34,160 fileinput INFO Read/parse ok for file=sql/create-tables.sql
2021-04-23 18:09:34,160 fileinput INFO all files done
2021-04-23 18:09:34,160 dboutput INFO executing SQL
2021-04-23 18:09:34,160 postgis INFO Connecting to dbname=bagv2 user=bas host=localhost port=5432
2021-04-23 18:09:34,170 postgis DEBUG Connected to database bagv2
2021-04-23 18:09:34,174 postgis ERROR error type "geometry" does not exist
LINE 43:     geovlak geometry(Polygon, 28992),
                     ^
```

De database is aangemaakt met:
```
su - postgres
createdb bagv2 -O bas
echo "CREATE EXTENSION postgis;" | psql bagv2
```

Configuratie:
```
$ cat options/$(hostname).args | sed 's/password=.*/password=<password>/'
# Default options for the Stetl BAG v2 Stetl ETL Chains

# These values are substituted into the ETL conf in conf/etl-imbag-v2.1.0.cfg, see the {arg} strings there

# INPUT: gml files, point to directory or file(s) pattern
bag_input_file=test/data/lv/BAGNLDL-15092020-small.zip
bag_file_ext=zip

# OUTPUT: PostGIS settings
pg_host=isis
pg_port=5432
pg_user=bas
password=<password>
pg_db=bagv2
schema=public
```
Het gebruikt van het `test` schema maakt geen verschil.

Voor BAGv1 wordt `SET search_path` gebruikt:
```
'SET search_path TO %s,public' % self.config.schema
```

Voor BAGv2 wordt dat alleen voor `test/test-gdal-perf.sh` gedaan.

**Comment by sebastic** [comment]
Deze change werkt voor mij:
```diff
--- a/bagv2/etl/sql/create-tables.sql
+++ b/bagv2/etl/sql/create-tables.sql
@@ -1,3 +1,5 @@
+CREATE EXTENSION postgis;
+
 -- Tabellen voor BAG-Extract v2
 -- Min of meer 1-1 met BAG model dus niet geoptimaliseerd
 -- Te gebruiken als basis tabellen om specifieke tabellen
```
Dit is nodig omdat `sql/create-schema.sql` bij elke import het schema verwijderd waardoor postgis niet meer beschikbaar is:
```sql
$ cat sql/create-schema.sql 
-- Author: Just van den Broecke

-- Maak schema aan indien deze nog niet bestaat.
-- StringFilter vult actuele schema naam in.
DROP SCHEMA IF EXISTS {schema} CASCADE;
CREATE SCHEMA {schema};
```
Dit zou ook vervangen kunnen worden door:
```sql
-- Author: Just van den Broecke

-- Maak schema aan indien deze nog niet bestaat.
-- StringFilter vult actuele schema naam in.
CREATE SCHEMA IF NOT EXISTS {schema};
```
Daarmee doet het wat de comment beschrijft.

**Comment by justb4** [comment]
Denk dat dit komt omdat `public` schema wordt gebruikt en eerst wordt leeggemaakt, daardoor is `postgis` en mogelijke andere extensies, niet meer beschikbaar. Had je zelf ook gezien. Het is gebruikelijk om niet het `public` schema te gebruiken. Als alleen `CREATE SCHEMA IF NOT EXISTS {schema};` wordt gedaan, treden allerlei nieuwe problemen op indien schema en allerlei indexen etc bestaan. Voor inlezen BAGv2 willen we zeker zijn dat we met leeg schema beginnen. Maar dan is `public` problematisch. Commentaar klopt inderdaad niet.

**Comment by RnoldR** [comment]
Ik heb exact dezelfde foutmelding:

2021-12-29 16:34:51,688 fileinput INFO Read/parse ok for file=sql/create-tables.sql
2021-12-29 16:34:51,688 fileinput INFO all files done
2021-12-29 16:34:51,688 dboutput INFO executing SQL
2021-12-29 16:34:51,688 postgis INFO Connecting to dbname=bagv2 user=postgres host=host.docker.internal port=5432
2021-12-29 16:34:51,697 postgis DEBUG Connected to database bagv2
2021-12-29 16:34:51,701 postgis ERROR error type "geometry" does not exist
LINE 43:     geovlak geometry(Polygon, 28992),
                     ^
 in query: -- Tabellen voor BAG-Extract v2

De docker run opdracht:
`docker run  --name nlextract --add-host=host.docker.internal:host-gateway -v $(pwd)/work:/work nlextract/nlextract:latest bagv2/etl/etl.sh -a schema=doesburg -a bag_input_file=/work/bag`

Wat doe ik precies fout?

**Comment by raymondnijssen** [comment]
Je hebt de extensie postgis niet (juist) toegevoegd?

Run de query:
CREATE EXTENSION postgis;

**Comment by RnoldR** [comment]
Dat was het inderdaad. Ik had de foutieve aanname dat een Postgis dockerfile alle databases van een postgis extensie zou voorzien, dat was niet zo.

Hartelijk dank voor de info en je geduld!

**Comment by RnoldR** [comment]
Klopt, dank de suggestie van Raymond opgelost.
