### ISSUE TITLE
Postcode is niet bij alle adressen aanwezig

### ISSUE THREAD

**Issue by pkruithof** [nlextract/NLExtract#320]
Ik weet niet zeker of ik dit soort issues hier moet melden, excuus als dit niet zo is.

Wij nemen inmiddels de betaalde versie van nlextract af. Bij de laatste versie die we hebben aangeschaft (`20210408`) valt me op dat niet alle adressen een postcode hebben:

```
select count(*) from bagactueel.adres_full where postcode is null;
# 183807
```

Eerdere versies hadden dit niet, onze laatste dateert van november vorig jaar in elk geval. Is dit een verwachte/geaccepteerde wijziging of zou dit altijd ingevuld moeten zijn?

**Comment by justb4** [comment]
@pkruithof Voor geotoko.nl is er een helpdesk: mail vragen/problemen naar support@geotoko.nl

Maar omdat het in de bron een NLExtract feature is, kan de vraag hier ook goed. De omgekeerde vraag is voorheen veel op de geotoko.nl helpdesk terecht gekomen: ontbrekende adressen. We hebben daarom per feb 2021 ook adressen zonder Postcode aan alle adres-bestanden (Basis, Uitgebreid(=full) en Woning(=plus)) toegevoegd. Voorheen was dit alleen in Woning (adres-plus in NLExtract). Alle adres-bestanden worden van Woning afgeleid, dus aantallen zijn identiek nu. 

Het ontbreken van Postcodes voor sommige adressen is per (BAG) design. Sommige adressen (BAG Nummeraanduidingen) hebben namelijk geen of nooit een Postcode:

*  bijv KPN en "PEN" huisjes
* nieuwbouw, Postcode moet nog uitgegeven, althans staat nog niet in BAG

We willen zo compleet mogelijke adressen tabellen (In NLExtract) genereren. Adressen zonder Postcode kunnen altijd later uitgefilterd.

**Comment by pkruithof** [comment]
Helder, dan weet ik dat dit verwacht is en hou ik daar rekening mee in onze eigen set. Bedankt voor de toelichting!

Ik zie dat je het issue aan een milestone hebt toegevoegd. Ik weet niet of dat inhoudt dat er nog wat mee moet gebeuren, maar wat mij betreft kan ie hiermee gesloten worden hoor.

**Comment by justb4** [comment]
Ok, ja is eigenlijk geen issue, dus geen milestone nodig.
