### ISSUE TITLE
BGT Import crashed op panden

### ISSUE THREAD

**Issue by mwjhartogs** [nlextract/NLExtract#324]
Beste,

Ik lees geheel Nederland in (/bgt-citygml-nl-nopbp.zip' 19 GB groot). 

Dan krijg ik ongeveer na 8 uur processing de volgende error op panden. Heeft dit met een timeout te maken. Dit omdat panden veel langer in behandeling is dan de andere features.

2021-07-26 14:03:25,807 execoutput INFO execute done
2021-07-26 14:03:26,437 fileinput INFO Pop file record: {'file_path': '/input/bgt/bgt-citygml-nl-nopbp.zip', 'name': 'bgt_pand.gml'}
2021-07-26 14:06:36,459 subfeaturehandler INFO invoke() for imgeo:positie
2021-07-26 14:06:36,826 subfeaturehandler INFO skipping GML file for subfeat=imgeo:positie
2021-07-26 14:06:36,826 subfeaturehandler INFO invoke() for imgeo:nummeraanduidingreeks[imgeo:Nummeraanduidingreeks]
2021-07-26 14:06:36,837 subfeaturehandler INFO checkGmlFile: found parentTag {http://www.opengis.net/citygml/building/2.0}BuildingPart
./etl.sh: line 42:   515 Killed                  python $STETL_HOME/stetl/main.py -c conf/etl-imgeo-v2.1.1.cfg -a $options_file

Hopelijk een oplossing, omdat de foutmeldingen niet zo heel duidelijk is..

M

**Comment by justb4** [comment]
Meestal is dit een geheugenprobleem. `subfeaturehandler` is een heftig proces, omdat helaas binnen BGT oa voor Pand binnen elke GML element ook weer Nummeraanduiding element als 'subfeature' plaatst. Melding is vaker geweest:
https://gitter.im/nlextract/NLExtract?at=5f563dd99bad075eac03d85b

Het is wel handig om meer context te geven: OS, wel/geen Docker, en vooral RAM geheugen etc.

**Comment by mprins** [comment]
lichtelijk OT @matthijsln is bezig met afonden van een PR die de nachtelijke -nobp zip file in een paar uurtjes kan laden op een RPi 4 met SSD, op een snelle PC nog veel sneller https://github.com/B3Partners/brmo/pull/1114 ('t is wel Java, maar in een dockerimage dus dat voel je niet zo 😉 ) de tool kan ook mutaties ophalen/verwerken

**Comment by matthijsln** [comment]
> lichtelijk OT @matthijsln is bezig met afonden van een PR die de nachtelijke -nobp zip file in een paar uurtjes kan laden op een RPi 4 met SSD, op een snelle PC nog veel sneller [B3Partners/brmo#1114](https://github.com/B3Partners/brmo/pull/1114) ('t is wel Java, maar in een dockerimage dus dat voel je niet zo  ) de tool kan ook mutaties ophalen/verwerken

Een beknopte handleiding is voor nu [hier](https://github.com/B3Partners/brmo/tree/bgt-citygml-loader/bgt-loader) te vinden.
In het kort: als je het bestand "bgt-citygml-nl-nopbp.zip" in je lokale directory hebt staan, een lokale PostGIS database genaamd 'bgt' hebt gemaakt met de PostGIS extensies erin en een database gebruiker 'bgt' hebt met 'bgt' als wachtwoord, kan je de BGT inladen met:
```
docker run -it --rm --network=host -v $(pwd):/data ghcr.io/b3partners/brmo-bgt-loader load /data/bgt-citygml-nl-nopbp.zip
```
Of zonder eerst het hele bestand te moeten downloaden:
```
docker run -it --rm --network=host ghcr.io/b3partners/brmo-bgt-loader load https://api.pdok.nl/lv/bgt/download/v1_0/full/predefined/bgt-citygml-nl-nopbp.zip
```
Een stand inladen die dagelijks met alleen de dagelijkse mutaties kan worden bijgewerkt kan ook, maar omdat die eerst door PDOK moet worden gemaakt duurt dat voor de _hele_ BGT een stuk langer.

**Comment by justb4** [comment]
Niet zo smaakvol om dit binnen een issue van NLExtract te vermelden, zonder dat de hele context bekend is. "Een paar uurtjes" duurt normaal de BGT ook met NLExtract en er is nog veel optimalisatie mogelijk m.n. in multi-processing/threading. 
Voorbeeld: ik ben fan van MapServer. Maar ik ga niet, en zeker niet bij een on-geanalyseerd performance issue op de GeoServer-GitHub dan MapServer aanbieden. Not done. 
Diversiteit en keuze binnen Open Source is prima, maar dan beter op een neutraler kanaal als GeoForum waar aan de lopende band vragen over basisregistraties inlezen worden gesteld. Hier verborgen in dit issue wordt daar ook niemand wijzer van. Even goede vrienden, we kennen elkaar, maar hopelijk kunnen jullie @mprins @matthijsln mijn lichte irritatie begrijpen :-).

**Comment by mwjhartogs** [comment]
> Meestal is dit een geheugenprobleem. `subfeaturehandler` is een heftig proces, omdat helaas binnen BGT oa voor Pand binnen elke GML element ook weer Nummeraanduiding element als 'subfeature' plaatst. Melding is vaker geweest:
> https://gitter.im/nlextract/NLExtract?at=5f563dd99bad075eac03d85b
> 
> Het is wel handig om meer context te geven: OS, wel/geen Docker, en vooral RAM geheugen etc.

**Comment by mwjhartogs** [comment]
> Meestal is dit een geheugenprobleem. `subfeaturehandler` is een heftig proces, omdat helaas binnen BGT oa voor Pand binnen elke GML element ook weer Nummeraanduiding element als 'subfeature' plaatst. Melding is vaker geweest:
> https://gitter.im/nlextract/NLExtract?at=5f563dd99bad075eac03d85b
> 
> Het is wel handig om meer context te geven: OS, wel/geen Docker, en vooral RAM geheugen etc.

Beste Just,

Het id idd een probleem met het geheugen. Ik had het proces in een docker container gedraaid. Server had 16GB aan geheugen.  Geprobeerd eerst een quick fix uit te voeren door het geheugen op de VPS op te hogen naar 24GB, maar dit was ook niet genoeg. De huidige BGT importer probeert nu de kaartbladen te downloaden, maar die bestaan helaas niet meer in de nieuwe download service. 

Mocht je interesse hebben, heb even snel een nieuwe downloader geschreven in python, evt later een pull request:

```
import requests
import json
import time
import wget
import os


pdokapiurl = 'https://api.pdok.nl'
pdokbgturl = pdokapiurl + '/lv/bgt/download/v1_0/full/custom'
downloadlocation = '/home/NLExtract/bgt/etl/download/'

grids = [
"POLYGON ((185425.156 621876.3,210425.156 621876.3,210425.156 596876.3,185425.156 596876.3,185425.156 621876.3))",
"POLYGON ((260425.156 596876.3,285425.156 596876.3,285425.156 571876.3,260425.156 571876.3,260425.156 596876.3))",
"POLYGON ((260425.156 571876.3,285425.156 571876.3,285425.156 546876.3,260425.156 546876.3,260425.156 571876.3))",
"POLYGON ((260425.156 546876.3,285425.156 546876.3,285425.156 521876.3,260425.156 521876.3,260425.156 546876.3))",
"POLYGON ((260425.156 521876.3,285425.156 521876.3,285425.156 496876.3,260425.156 496876.3,260425.156 521876.3))",
"POLYGON ((160425.156 371876.3,185425.156 371876.3,185425.156 346876.3,160425.156 346876.3,160425.156 371876.3))",
"POLYGON ((160425.156 346876.3,185425.156 346876.3,185425.156 321876.3,160425.156 321876.3,160425.156 346876.3))",
"POLYGON ((160425.156 321876.3,185425.156 321876.3,185425.156 296876.3,160425.156 296876.3,160425.156 321876.3))",
"POLYGON ((35425.156 371876.3,60425.156 371876.3,60425.156 346876.3,35425.156 346876.3,35425.156 371876.3))",
"POLYGON ((260425.156 621876.3,285425.156 621876.3,285425.156 596876.3,260425.156 596876.3,260425.156 621876.3))",
"POLYGON ((35425.156 446876.3,60425.156 446876.3,60425.156 421876.3,35425.156 421876.3,35425.156 446876.3))",
"POLYGON ((35425.156 421876.3,60425.156 421876.3,60425.156 396876.3,35425.156 396876.3,35425.156 421876.3))",
"POLYGON ((85425.156 521876.3,110425.156 521876.3,110425.156 496876.3,85425.156 496876.3,85425.156 521876.3))",
"POLYGON ((185425.156 321876.3,210425.156 321876.3,210425.156 296876.3,185425.156 296876.3,185425.156 321876.3))",
"POLYGON ((85425.156 496876.3,110425.156 496876.3,110425.156 471876.3,85425.156 471876.3,85425.156 496876.3))",
"POLYGON ((210425.156 621876.3,235425.156 621876.3,235425.156 596876.3,210425.156 596876.3,210425.156 621876.3))",
"POLYGON ((85425.156 471876.3,110425.156 471876.3,110425.156 446876.3,85425.156 446876.3,85425.156 471876.3))",
"POLYGON ((185425.156 421876.3,210425.156 421876.3,210425.156 396876.3,185425.156 396876.3,185425.156 421876.3))",
"POLYGON ((185425.156 396876.3,210425.156 396876.3,210425.156 371876.3,185425.156 371876.3,185425.156 396876.3))",
"POLYGON ((85425.156 571876.3,110425.156 571876.3,110425.156 546876.3,85425.156 546876.3,85425.156 571876.3))",
"POLYGON ((185425.156 371876.3,210425.156 371876.3,210425.156 346876.3,185425.156 346876.3,185425.156 371876.3))",
"POLYGON ((85425.156 546876.3,110425.156 546876.3,110425.156 521876.3,85425.156 521876.3,85425.156 546876.3))",
"POLYGON ((185425.156 346876.3,210425.156 346876.3,210425.156 321876.3,185425.156 321876.3,185425.156 346876.3))",
"POLYGON ((60425.156 396876.3,85425.156 396876.3,85425.156 371876.3,60425.156 371876.3,60425.156 396876.3))",
"POLYGON ((60425.156 371876.3,85425.156 371876.3,85425.156 346876.3,60425.156 346876.3,60425.156 371876.3))",
"POLYGON ((185425.156 446876.3,210425.156 446876.3,210425.156 421876.3,185425.156 421876.3,185425.156 446876.3))",
"POLYGON ((60425.156 471876.3,85425.156 471876.3,85425.156 446876.3,60425.156 446876.3,60425.156 471876.3))",
"POLYGON ((235425.156 471876.3,260425.156 471876.3,260425.156 446876.3,235425.156 446876.3,235425.156 471876.3))",
"POLYGON ((60425.156 446876.3,85425.156 446876.3,85425.156 421876.3,60425.156 421876.3,60425.156 446876.3))",
"POLYGON ((235425.156 446876.3,260425.156 446876.3,260425.156 421876.3,235425.156 421876.3,235425.156 446876.3))",
"POLYGON ((110425.156 396876.3,135425.156 396876.3,135425.156 371876.3,110425.156 371876.3,110425.156 396876.3))",
"POLYGON ((235425.156 521876.3,260425.156 521876.3,260425.156 496876.3,235425.156 496876.3,235425.156 521876.3))",
"POLYGON ((235425.156 496876.3,260425.156 496876.3,260425.156 471876.3,235425.156 471876.3,235425.156 496876.3))",
"POLYGON ((235425.156 621876.3,260425.156 621876.3,260425.156 596876.3,235425.156 596876.3,235425.156 621876.3))",
"POLYGON ((210425.156 446876.3,235425.156 446876.3,235425.156 421876.3,210425.156 421876.3,210425.156 446876.3))",
"POLYGON ((110425.156 596876.3,135425.156 596876.3,135425.156 571876.3,110425.156 571876.3,110425.156 596876.3))",
"POLYGON ((210425.156 396876.3,235425.156 396876.3,235425.156 371876.3,210425.156 371876.3,210425.156 396876.3))",
"POLYGON ((110425.156 571876.3,135425.156 571876.3,135425.156 546876.3,110425.156 546876.3,110425.156 571876.3))",
"POLYGON ((210425.156 371876.3,235425.156 371876.3,235425.156 346876.3,210425.156 346876.3,210425.156 371876.3))",
"POLYGON ((135425.156 371876.3,160425.156 371876.3,160425.156 346876.3,135425.156 346876.3,135425.156 371876.3))",
"POLYGON ((85425.156 396876.3,110425.156 396876.3,110425.156 371876.3,85425.156 371876.3,85425.156 396876.3))",
"POLYGON ((160425.156 621876.3,185425.156 621876.3,185425.156 596876.3,160425.156 596876.3,160425.156 621876.3))",
"POLYGON ((135425.156 396876.3,160425.156 396876.3,160425.156 371876.3,135425.156 371876.3,135425.156 396876.3))",
"POLYGON ((10425.156 421876.3,35425.156 421876.3,35425.156 396876.3,10425.156 396876.3,10425.156 421876.3))",
"POLYGON ((10425.156 396876.3,35425.156 396876.3,35425.156 371876.3,10425.156 371876.3,10425.156 396876.3))",
"POLYGON ((10425.156 371876.3,35425.156 371876.3,35425.156 346876.3,10425.156 346876.3,10425.156 371876.3))",
"POLYGON ((260425.156 496876.3,285425.156 496876.3,285425.156 471876.3,260425.156 471876.3,260425.156 496876.3))",
"POLYGON ((135425.156 621876.3,160425.156 621876.3,160425.156 596876.3,135425.156 596876.3,135425.156 621876.3))",
"POLYGON ((260425.156 471876.3,285425.156 471876.3,285425.156 446876.3,260425.156 446876.3,260425.156 471876.3))",
"POLYGON ((135425.156 596876.3,160425.156 596876.3,160425.156 571876.3,135425.156 571876.3,135425.156 596876.3))"
]


for grid in grids:
	body = '{"format":"citygml","featuretypes":["bak","begroeidterreindeel","bord","buurt","functioneelgebied","gebouwinstallatie","installatie","kast","kunstwerkdeel","mast","onbegroeidterreindeel","ondersteunendwaterdeel","ondersteunendwegdeel","ongeclassificeerdobject","openbareruimte","openbareruimtelabel","overbruggingsdeel","overigbouwwerk","overigescheiding","paal","pand","put","scheiding","sensor","spoor","stadsdeel","straatmeubilair","tunneldeel","vegetatieobject","waterdeel","waterinrichtingselement","waterschap","wegdeel","weginrichtingselement","wijk"],"geofilter":"'+grid+'"}'
	response = requests.post(pdokbgturl, data=body,headers={"Content-Type": "application/json"})
	print("Status code: ", response.status_code)
	
	jsoncontent = response.json() 
	print(jsoncontent["downloadRequestId"])
	guid=jsoncontent["downloadRequestId"]
	statusurl=  pdokbgturl + '/' + guid + '/status'
	content	= True
	while content: 
		statusreq = requests.get(url = statusurl)
		statusdata = statusreq.json()
		status = statusdata["status"]
		link = statusdata["_links"]
		print(status)	
		if (status!='RUNNING' and  status!='PENDING'): 
			if (status=='COMPLETED'):
				href = link["download"]
				downloadurl = pdokapiurl + href["href"]
				print(downloadurl)
				wget.download(downloadurl, downloadlocation)
				old_file_name = downloadlocation + 'extract.zip'
				new_file_name = downloadlocation + guid + '.zip'
				os.rename(old_file_name, new_file_name)
			content = False
		time.sleep(20)
print('Download bgt complete')
```
	
  
	
Bedankt voor je hulp

Mvg,

Miguel Hartogs
Merkator & GeoAI

**Comment by justb4** [comment]
@mwjhartogs bedankt voor de inzichten en code. Ik draai zelf "BGT" landelijke download, op 32GB RAM op een VPS maar check eerst hoeveel geheugen Docker krijgt. Zie bijv [dit issue](https://github.com/nlextract/NLExtract/issues/310). Weliswaar voor BAG, maar ik heb gezien dat hoewel het OS 32GB RAM had, de Docker Engine/Desktop maar 4GB kreeg (bijv met Docker Desktop op Mac OSX). Die moet je dan verhogen. Maar goed je zit op een VPS. De BGT groeit als kool, hoewel dat met de Panden wel mee zal vallen. 32 GB moet in ieder geval genoeg zijn. Voor "gewone" GML files maakt de grootte niet uit: de onderliggende ETL engine Stetl werkt "streaming": de GML wordt niet eerst in geheugen ingelezen/geparsed. Bij mijn weten ook voor subfeatures in BGT Pand. Er zijn ook nog settings in "options" voor "max_features".

**Comment by justb4** [comment]
m.i. opgelost, sluiten, heropen indien nog steeds probleem.
