### ISSUE TITLE
psycopg2.errors.UndefinedColumn: column "aanduidingRecordInactief" of relation "ligplaats" does not exist

### ISSUE THREAD

**Issue by ypj0202** [nlextract/NLExtract#347]
Dag, toen ik de BAG gegevens aan het extraheren was met behulp van `/bag/test/runadres.sh` met versie 1.5.3, kwam ik de fout tegen die in de titel wordt genoemd. Na wat onderzoek en graven, kon ik geen oplossing vinden, enig idee jongens?<br>
Mijn omgeving:
- Ubuntu 20.04
- Python 3.8.10
### Screenshot
![image](https://user-images.githubusercontent.com/65748477/154772620-f9ac818f-cadd-4b64-b14b-85731d68e218.png)
<br>Ik heb ook de kolom in de database gecontroleerd die `aanduidingRecordInactief` is in de tabel `ligplaats`<br>
![image](https://user-images.githubusercontent.com/65748477/154772930-d2ec58fe-b1cd-49d3-b5e7-de86cc2e6f10.png)

**Comment by justb4** [comment]
@ypj0202 het lijkt erop dat je BAG versie 1 probeert. Deze is uitgefaseerd. Je moet BAG versie 2 hebben onder de map [bagv2](https://github.com/nlextract/NLExtract/tree/master/bagv2).

**Comment by ypj0202** [comment]
> @ypj0202 het lijkt erop dat je BAG versie 1 probeert. Deze is uitgefaseerd door Kadaster, wordt niet meer geleverd. Je moet BAG versie 2 hebben onder de map [bagv2](https://github.com/nlextract/NLExtract/tree/master/bagv2).

Bedankt voor je antwoord @justb4, de reden dat ik nog steeds BAGv1 gebruik is dat BAGv2 meer tijd verbruikt dan BAGv1 en meer opslagruimte inneemt op mijn harde schijf.
### Verbruikte tijd
``
INFO: 22-02-22 07:24:32 - Using options_file=/root/new/nlextract-1.5.3/bagv2/etl/options/default.args and user_args=-c conf/etl-imbag-2.1.0.cfg -a bag_input_file=/root/bag.zip
`` **(Toen ik het script startte)**
``
2022-02-22 21:11:53,621 postgis DEBUG Connected to database bagv2
`` **(Voordat ik mijn laptop uitzet, draait het script nog steeds...)**<br>
**Voor BAGv1, kostte het mij slechts 6~7 uur om het te ontleden en in te voegen in de database**

### Opslag bezetting 
Ik draai BAGv1 en BAGv2 in twee gescheiden WSL Ubuntu 20.04 omgevingen, hieronder zie je het verschil in opslagbezetting op mijn harde schijf (links BAGv1, rechts BAGv2)
![image](https://user-images.githubusercontent.com/65748477/155224001-0d07a03e-cded-4dff-8158-7d0630ca32e3.png)<br>
Daarom zou enige hulp, suggesties en commentaar om het probleem op te lossen dat ik tegenkwam in BAGv1 op prijs worden gesteld!

**Comment by justb4** [comment]
@ypj0202 BAG v1 wordt niet meer geleverd door Kadaster. Jouw GitHub account is ook lekker vaag: https://github.com/ypj0202  , zonder significante bijdragen, redelijk anoniem lijkt het, dat kan/magl maar dan kan je ook niet veel (gratis) support verwachten...

**Comment by justb4** [comment]
Was meer vraag en beantwoord, sluiten..
