### ISSUE TITLE
Top10NL download url verouderd

### ISSUE THREAD

**Issue by nvandegevelSobolt** [nlextract/NLExtract#364]
De url om top10nl bestanden te downloaden is net meer beschikbaar:
http://geodata.nationaalgeoregister.nl/TOP10nlv2/extract/kaartbladtotaal/TOP10nl.zip?formaat=gml.

De url in de top10NL handleiding is ook niet meer beschikbaar:
https://www.pdok.nl/nl/producten/pdok-downloads/basis-registratie-topografie/topnl/topnl-actueel/TOP10nl

PDOK geeft aan dat dit de nieuwe werkwijze is om data en losse kaartbladen te downloaden:
https://www.pdok.nl/atom-downloadservices/-/article/basisregistratie-topografie-brt-topnl

**Comment by justb4** [comment]
Documentatie aangepast: https://docs.nlextract.nl/en/latest/brtextract.html .
