### ISSUE TITLE
Fallback van lxml/etree  naar cElementTree werkt niet

### ISSUE THREAD

**Issue by justb4** [nlextract/NLExtract#72]
Als lxml/etree niet installed is zou een fallback gedaan moeten worden naar cElementTree. Dit gebeurt op zich wel, maar vervolgens treedt er een parsing error op (iets met Namespaces). 
Als de eerste logging melding is  "running with cElementTree" is lxml niet geinstalleerd/aktief. 

vervolgens deze error:

> ERROR: fout nsmap in DOM processing,
> bestand=9999LIG08042012-000001.xml ['Traceback (most recent call last):
> \n', '  File "D:\install\nlextract\nlextract-1.1.0\bag\src\
> \bagfilereader.py", line 145, in processXML\n
> self.processor.processDOM(xmldoc)\n', '  File "D:\install\nlextract\
> \nlextract-1.1.0\bag\src\processor.py", line 70, in processDOM\n
> self.bagObjecten =
> BAGObjectFabriek.bof.BAGObjectArrayBijXML(productnode)\n', '  File "D:\
> \install\nlextract\nlextract-1.1.0\bag\src\bagobject.py", line
> 477, in BAGObjectArrayBijXML\n    bagObject =
> self.BAGObjectBijXML(node)\n', '  File "D:\install\nlextract\
> \nlextract-1.1.0\bag\src\bagobject.py", line 470, in BAGObjectBijXML
> \n    bagObject.leesUitXML(node)\n', '  File "D:\install\nlextract\
> \nlextract-1.1.0\bag\src\bagobject.py", line 94, in leesUitXML\n
> attribuut.leesUitXML(xml)\n', '  File "D:\install\nlextract\
> \nlextract-1.1.0\bag\src\bagattribuut.py", line 119, in leesUitXML
> \n    self._waarde = getValue(xml, self._tag)\n', '  File "D:\install\
> \nlextract\nlextract-1.1.0\bag\src\bagattribuut.py", line 42, in
> getValue\n    values = getValues(parent, tag)\n', '  File "D:\install\
> \nlextract\nlextract-1.1.0\bag\src\bagattribuut.py", line 37, in
> getValues\n    return [node.text for node in parent.iterfind(\'./\' +
> tagVolledigeNS(tag, parent.nsmap))]\n', 'AttributeError: nsmap\n']

**Comment by justb4** [comment]
Toch weer even uitstellen...BAG Extract zonder lxml lijkt mij sowieso een ramp....

**Comment by skinkie** [comment]
Goed om te weten, ik denk dat nsmap dus een lxml specifieke extensie is.

**Comment by MarcoDuiker** [comment]
Met enige creativiteit kan wellicht toch om de lxml requirement worden heengewerkt. 
findall ondersteunt op zich wel netjes samenspaces.

Voor de BGT heb de lxml implementatie herschreven naar xml-etree en dat werkt prima:

```
def _duplicateOrl_ugly(elem):
    '''
    A private helper function for the processing of openbareruimte labels.
    
    Adapted (a lot) from NLExtract.
    '''

    out_elem = deepcopy(elem)
    ns = {'imgeo': 'http://www.geostandaarden.nl/imgeo/2.1'}
    count = len(out_elem.findall('.//imgeo:positie', namespaces=ns))

    xml_string = ''
    for i in range(0, count):
        out_elem = deepcopy(elem)
        for el in out_elem.iter():
            if el.tag == '{http://www.geostandaarden.nl/imgeo/2.1}Label':
                j=0
                for child in el.getchildren():
                    if child.tag == '{http://www.geostandaarden.nl/imgeo/2.1}positie':
                        if not j == i:
                            el.remove(child) 
                        j = j + 1
        xml_string = xml_string + str(ET.tostring(out_elem, encoding = 'utf-8'))
        
    return xml_string 

def _process_ORL_ugly(task, orl_gml, tmp_folder):
    '''
    A private helper function to process OpenbareRuimteLabel.
    It duplicate features so that all labels will be shown.

    It avoids using lxml as that is a major hassle under windows.
    Of course, this implementation has a small memory footprint but it is rather ugly.
    '''

    input_gml = os.path.join(tmp_folder, orl_gml)
    temp_file = os.path.join(tmp_folder, 'bgt_orl.gml')

    nsmap = {None: "http://www.opengis.net/citygml/2.0"}

    header = '''<?xml version="1.0" encoding="UTF-8"?>
<CityModel xmlns:gml="http://www.opengis.net/gml" xmlns:imgeo="http://www.geostandaarden.nl/imgeo/2.1" xmlns="http://www.opengis.net/citygml/2.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.geostandaarden.nl/imgeo/2.1 http://schemas.geonovum.nl/imgeo/2.1/imgeo-2.1.1.xsd">'''

    footer = '''</CityModel>'''

    try:
        with open(temp_file, 'w') as xf:
            with open(input_gml,'rb') as f:
                xf.write(header)
                context = ET.iterparse(f)
                for action, elem in context:
                    if action == 'end' and elem.tag == '{http://www.opengis.net/citygml/2.0}cityObjectMember':
                        # Duplicate openbareruimtelabel
                        xf.write(_duplicateOrl_ugly(elem))
                        # Clean up the original element and the node of its previous sibling
                        # (https://www.ibm.com/developerworks/xml/library/x-hiperfparse/)
                        elem.clear()
                del context
            xf.write(footer)

```

**Comment by justb4** [comment]
Dit is BAGv1, geen actieve ontwikkeling meer. Sluiten dus.
